cookbooks/collectd/templates/default/collectd.conf.erb

(opened on behalf of @crigor)
This sends a collectd notification every 5 or 6 minutes. AWSM will disregard alerts within 1 hour so essentially this will generate disk alerts every hour.
The current behavior sends 1 alert on state change (warning -> failure or okay -> failure). If you miss that one failure alert you'll never get notified again.
This affects warning too though. So if your disk is in the warning level you'll get an hourly alert and email.

Make disk alerts persistent

---

cookbooks/php/attributes/php.rb

-------------
Updated PHP 5.6 to 5.6.25 for security fixes
-------------
Update PHP to 5.6.25.
Estimated risk
-------------
Low
-------------
PHP
-------------
Ran Chef with change without errors and  verified the php version with `php -v` lists `PHP 5.6.25-pl0-gentoo` at the beginning of the banner
-------------
1. Ensure chef completes successfully and app deploys and runs as expected
1. Upgrade to target stack
1. Verify chef run completes successfully
1. Verify the php version with `php -v` lists `PHP 5.6.25-pl0-gentoo` at the beginning of the banner
1. Terminate and recreate environment on target stack
1. Verify chef run completes …

CC-1038 PHP 5.6 Security Updates

---

cookbooks/nginx/recipes/configure.rb

-------------
Fixed /var/lib/nginx/tmp permissions on creation for uploads via nginx
-------------
Fix tmp permissions for nginx uploads
Estimated risk
-------------
Low
-------------
Nginx
-------------
Ran Chef with change without errors
-------------
1. Ensure chef completes successfully and app deploys and runs as expected
1. Upgrade to target stack
1. Verify chef run completes successfully
1. Verify the correct permissions and owners on `/var/lib/nginx/tmp` with ls -lah  are 755 and deploy: nginx
1. Terminate and recreate environment on target stack
1. Verify chef run completes successfully
1. Verify the correct permissions and …

CC-1030 /var/lib/nginx/tmp permissions

---

cookbooks/nginx/recipes/configure.rb
cookbooks/nginx/recipes/default.rb

-------------
Fixed /var/lib/nginx/tmp permissions on creation for uploads via nginx
-------------
Fix tmp permissions for nginx uploads
Estimated risk
-------------
Low
-------------
Nginx
-------------
Ran Chef with change without errors and verified correct permissions
-------------
1. Ensure chef completes successfully and app deploys and runs as expected
1. Upgrade to target stack
1. Verify chef run completes successfully
1. Verify the correct permissions and owners on `/var/lib/nginx/tmp` with ls -lah  are 755 and deploy: nginx
1. Terminate and recreate environment on target stack
1. Verify chef run completes successfully
1. Verify …

CC-1030 /var/lib/nginx/tmp permission change

---

cookbooks/node/attributes/node.rb
cookbooks/node/recipes/common.rb

-------------
Enable Libuv 1.9.1
-------------
Resolve an issue installing NodeJS 6.4.0
Estimated risk
-------------
Low
-------------
Nodejs
-------------
Ran Chef with change and verified that running `emerge -g =net-libs-6.4.0` installs without errors
-------------
1. Running `emerge -g =net-libs-6.4.0` will not run on the instance
1. Upgrade to target stack
1. Verify chef run completes successfully
1. Verify `emerge -g =net-libs-6.4.0` runs correctly
1. Terminate and recreate environment on target stack
1. Verify chef run completes successfully
1. Verify `emerge -g =net-libs-6.4.0` runs correctly

CC-1044 Libuv For Nodejs 6.4.0

---

cookbooks/sequelizejs/recipes/default.rb
cookbooks/sequelizejs/templates/default/config.json.erb

Previously, the sequelizejs recipe generates a config.json with a hardcoded framework env `production`. This causes issues if you use the recipe in environments with NODE_ENV not set to "production". This fix will get the environment from `node[:dna][:environment][:framework_env]` to generate the proper config.json.
I have tested this against the basic-chat app with NODE_ENV set to "development".

Fix sequelizejs to use framework_env variable.

---

cookbooks/nginx/recipes/default.rb

https://tickets.engineyard.com/issue/CC-1051
When a customer updates their SSL Certificate, then clicks Apply on the environment dashboard, the SSL Certificate is updated in the server (/etc/nginx/ssl/<cert_file>) but HAProxy continues to serve the old certificate. HAProxy needs to be reloaded for it to start serving the updated certificate.
We should automatically reload HAProxy on Apply if the SSL certificate of the environment has changed.

add haproxy restart for .pem template

---

cookbooks/elasticsearch/README.md
cookbooks/elasticsearch/attributes/default.rb
cookbooks/elasticsearch/definitions/plugin.rb
cookbooks/elasticsearch/files/default/elasticsearch.logrotate
cookbooks/elasticsearch/metadata.rb
cookbooks/elasticsearch/recipes/configure_cluster.rb
cookbooks/elasticsearch/recipes/default.rb
cookbooks/elasticsearch/recipes/download.rb
cookbooks/elasticsearch/recipes/install.rb
cookbooks/elasticsearch/templates/default/elasticsearch.in.sh.erb
cookbooks/elasticsearch/templates/default/elasticsearch.monitrc.erb
cookbooks/elasticsearch/templates/default/elasticsearch.yml.erb
cookbooks/elasticsearch/templates/default/es.yml.erb
cookbooks/elasticsearch/templates/default/logging.yml.erb
examples/elasticsearch/README.md
examples/elasticsearch/cookbooks/custom-elasticsearch/README.md
examples/elasticsearch/cookbooks/custom-elasticsearch/attribues/default.rb
examples/elasticsearch/cookbooks/custom-elasticsearch/metadata.rb
examples/elasticsearch/cookbooks/custom-elasticsearch/recipes/default.rb
examples/elasticsearch/cookbooks/ey-custom/metadata.rb
examples/elasticsearch/cookbooks/ey-custom/recipes/after-main.rb

* V4 recipe has been cleaned up. Code duplication between `recipes/default.rb` and `recipes/non_util.rb` has been removed.
* The code for S3 support aren't being called and appears to be unused was removed
* The monit health check URL has been changed to `/` from `/_cat/health` in the V4 recipe. The newer monit on V5 is more sensitive and is reporting false positives on `/_cat/health`
* `/usr/lib/elasticsearch/bin/elasticsearch` needs to be started with the `-d` option, otherwise the newer monit will think the process has turned zombie and will terminate it.

Elasticsearch 2.4.0

---

cookbooks/node/attributes/node.rb

-------------
Removed non-eselectable nodejs versions from available nodejs file and added updated 6.7.0 and 4.6.0 to available versions
-------------
Updates nodejs available versions to only list valid eselectable targets and updates available versions.
Estimated risk
-------------
Low
-------------
Nodejs
-------------
Ran Chef with change and verified that main chef completes
-------------
1. Verify chef completes
1. Upgrade to new stack and verify chef completes
1. Build environment on new stack and verify chef completes

CC-1056 CC-1055 Remove non-eselect and update nodejs versions

---

cookbooks/node/attributes/node.rb
cookbooks/node/recipes/common.rb

-------------
Enable The Non-Ruby Version Selection Feature to work for selecting NodeJS. This removes the previous aggregation of apps on the instance to figure out what version should be being run and uses the nodejs version selection.
-------------
This release allows Nodejs versions to be selected for Nodejs, Ruby, PHP Environments and ensures that the "nodejs_version" metadata on a per environment basis for Stable V5. When upgrading please have support enable the `Non-Ruby Version Selection Feature` to your account. 
Estimated risk
-------------
High
-------------
Nodejs
-------------
Ran Chef with change and verified that running `node -v` returned 4.4.5, 5.11.0, 6.4.0 and if another …

CC-1048 NodeJS dashboard selection

---

cookbooks/ey-lib/libraries/ey-environment.rb

improper package name. missing underscore

fix typo for ruby2.0.0_p648

---

cookbooks/unicorn/recipes/install.rb

rack 2.0.1 was released last June 30. It requires Ruby 2.2.2.
For environments using the Unicorn stack, our main chef installs Unicorn 4.1.1 which has "rack >= 0" as a production dependency. This ends up installing rack 2.0.1 which breaks on pre-Ruby 2.2.2 environments.
This fix installs rack 1.6.4 before installing Unicorn 4.1.1. Before rack 2.0.1 was released, Unicorn 4.1.1 already installs rack 1.6.4, so there is no change from the behaviour we had before June 30.
Related YT: https://tickets.engineyard.com/issue/CC-1010
Installs rack 1.6.4 before installing Unicorn, to get around rack 2.0.1's dependency on Ruby 2.2.
Minimal. Applications that use rack 1.6.4 will behave just like before. I tested against an application with Unicorn 5.1.0 and rack 2.0.1 on the Gemfile - the app was …

CC-1062 Install rack 1.6.4 before installing Unicorn

---

cookbooks/ebs/recipes/default.rb
cookbooks/postgresql/recipes/server_configure.rb

Adds a 2 hour timeout to Postgres startups and EBS volume resizes. On very large volumes these processes can exceed the 3600 second (1 hour) default timeout of chef.
Improve the reliability of chef when starting up Postgres on newly created servers.
Improve the reliability of chef when booting instances with volumes larger than 2TB.
Low
- This setting is already in place for MySQL, this just expands it to two additional resources that need it.
cookbooks/ebs/recipes/default.rb
cookbooks/postgresql9/recipes/server_configure.rb
- Provisioned a Postgres database cluster using the updated stack, in edit environment make sure not to enable ext4
- Added a replica database with a 3TB volume:
- Validated result:
- The instance started …

add 2 hour timeout on postgres starts and EBS volume resizes

---

cookbooks/node/templates/default/node.god.erb

This patch changes the way node processes are stopped, resulting in a more targeted 'kill' which terminates only the desired processes and nothing else.
Related YT: https://tickets.engineyard.com/issue/ENG-1108
Fixes issues when stopping NodeJS applications upon a deploy.
Medium. 
main chef Cookbooks.
See QA instructions.
1. Boot an environment with a NodeJS stack and a NodeJS test app.
2. Check that file `/etc/god/<app_name>/node.rb` contains the line:
```
w.stop = "/bin/kill -SIGINT -`cat /var/run/god/node-#{app_name}.pid`"
```
3. Upgrade to target stack.
4. Check that file `/etc/god/<app_name>/node.rb` contains the line:
```
w.stop = "/usr/bin/pkill -SIGINT -g `cat /var/run/god/node-#{app_name}.pid`"
```
5. Deploy the application several times, checking that:
- Deploy shouldn't fail
- …

Use pkill to stop node's process group

---

cookbooks/collectd/files/default/collectd_nanny
cookbooks/collectd/recipes/default.rb
cookbooks/collectd/recipes/httpd.rb

Adds collectd_nanny script to terminate stuck workers, and restart collectd daily.
Upgrades rrdtool to allow for performance graphs on the cloud dashboard.
Corrects configuration for stats to pull password from correct location in the metadata
Fixes missing performance graphs on the cloud dashboard.
Adds functionality to improve stability of collectd monitoring.
Low
- Fixes existing broken content
- Adds script that resets collectd daily
cookbooks/collectd/files/default/collectd_nanny
cookbooks/collectd/recipes/default.rb
cookbooks/collectd/recipes/httpd.rb
- Provisioned a cluster using the existing Stack with automatic version upgrades disabled (default)
- In the dashboard accessed the "Performance graphs" URL and selected one of …

fixes for collectd and rrdtool

---

cookbooks/unicorn/recipes/install.rb

This adds a commit to CC-1062:
- Install rack 1.6.4 only if Ruby version < 2.2
rack 2.0.1 was released last June 30. It requires Ruby 2.2.2.
For environments using the Unicorn stack, our main chef installs Unicorn 4.1.1 which has "rack >= 0" as a production dependency. This ends up installing rack 2.0.1 which breaks on pre-Ruby 2.2.2 environments.
This fix installs rack 1.6.4 before installing Unicorn 4.1.1. Before rack 2.0.1 was released, Unicorn 4.1.1 already installs rack 1.6.4, so there is no change from the behaviour we had before June 30.
Related YT: https://tickets.engineyard.com/issue/CC-1010
Installs rack 1.6.4 before installing Unicorn, to get around rack 2.0.1's dependency on Ruby 2.2.
Minimal. Applications that use rack 1.6.4 will behave just like before. I tested against an …

CC-1062-1 Install rack 1.6.4 before installing Unicorn

---

cookbooks/cron/recipes/default.rb

This patch resolves an issue with cron jobs specified on the EY CLoud dashboard not being created on app_master
Related YT: https://tickets.engineyard.com/issue/Triage-9123
Resolves an issue with cron jobs specified on the EY CLoud dashboard not being created on app_master
Minimal. Only the cron recipe was updated.
A. Clustered environment
Boot an environment and create cron jobs on the dashboard
Verify that the cron jobs weren't created on the app_master instance. As the deploy user, run `crontab -l`
Upgrade to target stack
Verify that the cron jobs were created on the app_master instance
B. Solo environment
Boot an environment and create cron jobs on the dashboard
Verify that the cron jobs weren't created on the solo instance. As the deploy user, run `crontab -l` …

Add missing ['dna'] in node references

---

cookbooks/newrelic/providers/default.rb
cookbooks/newrelic/recipes/default.rb
cookbooks/newrelic/templates/default/newrelic-sysmond.init.erb
cookbooks/newrelic/templates/default/nrsysmond.monitrc.erb

This patch: 
- Fixes NewRelic server monitoring.
- Makes monit use start-stop-daemon for its actions when dealing with nrsysmond.
- Set hostname for reporting with a meaningful name.
Related YT: https://tickets.engineyard.com/issue/CC-1074
Fixes issues with NewRelic server monitoring.
Configures a meaningful hostname for reporting to NewRelic.
Minimal. 
main chef Cookbooks.
1. Boot an environment with any stack.
2. Enable NewRelic on the environment.
3. Verify que nothing is reported on the 'servers' section of NewRelic.
4. Upgrade to target stack.
5. Verify that information is recorded/displayed by NewRelic under with a server name in the form of '<amazon_id> - role - name' (name is only present if the instance has one). 
See testing done above.

CC-1074 Fix NewRelic server monitoring

---

cookbooks/ssmtp/recipes/default.rb

This patch installs ssmtp properly
Related YT: https://tickets.engineyard.com/issue/CC-1073
Resolves an issue with ssmtp not being installed properly
Minimal. 
1. Boot an environment on v5
2. Verify chef finishes
3. Verify `eix ssmtp` doesn't have an installed version
4. Upgrade to target stack
5. Verify chef finishes
6. Verify `eix ssmtp` has 2.64-r2 installed
See testing done above

CC-1073 Install SSMTP

---

cookbooks/collectd/files/default/check_health_for

- Modify collectd health check to eliminate the error "value too great for base" at 08 and 09 minutes after the hour. (CC-929)
- v5 only, modify interval check to output to a file to prevent collectd log messages "...check_health_for' has closed STDERR" (CC-1071)
- Reduces warnings created by interval controls of collectd `check_health_for`
Minimal, monitoring is in place that would alert to any disruptions.
git diff --name-only next-release
cookbooks/collectd/files/default/check_health_for
Deployed a 16.06 current stack with Postgres and validated that the presence of messages like the following in `/var/log/syslog`
`less /var/log/syslog |grep check_health |grep 'value too great'`
```
[2015-10-26 04:08:07] exec plugin: exec_read_one: error = /engineyard/bin/check_health_for: line 48: 08: …
```

Adjust collectd health check script to prevent syslog entries at minutes 1-9 of each hour

---

cookbooks/ey-lib/libraries/ey-application.rb

This patch resolves an issue with Passenger 5 and utility instances.
Related YT: https://tickets.engineyard.com/issue/CC-1060
Resolves an issue with Passenger 5 and utility instances
Minimal. 
1. Boot an environment with Passenger 5 and a utility instance
2. Verify chef fails on the utility instance
3. Upgrade to target stack
4. Verify chef completes on the utility instance
See testing done above

CC-1060 Passenger 5 not install on utils

---

cookbooks/nginx/recipes/default.rb

Description
-------------
Reload HAProxy when SSL certificate is updated. An older pull request #25 used restart, and that was reverted in #35. This new patch performs a `/etc/init.d/haproxy reload`.
-------------
Reloads HAProxy when SSL certificate is updated.
How to Test
-------------
* Create 2 self-signed certificates in https://cloud.engineyard.com/ssl_certificates. One can be named after the app master's hostname. The other can be named anything.
* Create a new environment using the latest stable-v5 stack.
* Assign any of the two SSL certificates to the environment. Click Apply.
* Check /etc/nginx/ssl/appname.pem. Take note of its timestamp. Also note the start time of the HAProxy process: `ps -ef | grep haproxy`.
* Try assigning the other SSL certificate …

CC-1051: Reload HAProxy for app.pem template.

---

cookbooks/postgresql/README.md
cookbooks/postgresql/attributes/extension_details.rb
cookbooks/postgresql/libraries/helpers.rb
cookbooks/postgresql/recipes/auto_explain.rb
cookbooks/postgresql/recipes/pg_stat_statements.rb
cookbooks/postgresql/recipes/postgis_build.rb
cookbooks/postgresql/recipes/server_configure.rb
cookbooks/postgresql/resources/pg_extension.rb

- pg_extension custom resource
- Specify core extensions to install via /db/postgresql/extensions.json
QA steps:
1. Boot Postgres env on QA stack with this branch already merged that has a db_slave.
2. Log into the db_master and run the following commands:
`createdb -O deploy foo`
`createdb -O deploy bar`
1. On both the db_master and db_slave create a file called `/db/postgresql/extensions.json` with this as it's contents:
```
{
"foo": ["isn, postgis"],
"bar": ["pg_buffercachem, pg_stat_statements"]
}
```
1. Run an Apply on the environment.
2. On both the db_master and db_slave run the following commands and verify that the relevant two extensions are listed for each db:
`psql -c '\dx' foo`
`psql -c '\dx' bar`

Postgres extensions support

---

cookbooks/mysql/templates/default/my.conf.erb

Sets a default value of `sync_binlog=0` for MySQL databases to improve performance under MySQL 5.7. MySQL versions < 5.7 default to 0, 5.7 defaults this to 1 which creates issues for database performance.
Default `sync_binlog` to 0 for MySQL 5.7 to improve binary logging performance.
Low
- This setting is the value used by prior instances of MySQL
- This setting really only changes things for MySQL 5.7 which is behind a feature flag anyway.
cookbooks/mysql/templates/default/my.conf.erb
Under the 12.11 stack
- Provisioned a cluster using the existing Stack running MySQL 5.7
- Ran:
- `mysql -NB -e "show global variables like 'sync_binlog'"`
- Validated result:
```
sync_binlog   1
```
- Deployed to tpol-2016 dev stack.
- Upgraded the environment.
- …

defaults sync_binlog to 0 for all MySQL versions

---

cookbooks/newrelic/providers/default.rb

This should address an issue present in PR #55

Fixed permissions for folder containing NR logs

---

cookbooks/collectd/files/default/check_health_for

- Modify collectd health check to eliminate the error "value too great for base" at 08 and 09 minutes after the hour. (CC-929)
- Reduces warnings created by interval controls of collectd `check_health_for`
Minimal, monitoring is in place that would alert to any disruptions.
git diff --name-only next-release
cookbooks/collectd/files/default/check_health_for
Deployed a 16.06 current stack with Postgres and validated that the presence of messages like the following in `/var/log/syslog`
`less /var/log/syslog |grep check_health |grep 'value too great'`
```
[2015-10-26 04:08:07] exec plugin: exec_read_one: error = /engineyard/bin/check_health_for: line 48: 08: value too great for base (error token is "08")
[2015-10-26 04:09:37] exec plugin: exec_read_one: error = …
```

reverts changes associated with CC-1071

---

cookbooks/php/attributes/php.rb

This is a minor patch to get the PR https://github.com/engineyard/ey-cookbooks-stable-v5/pull/61 to work.
dna.json uses `php_70`, not `php_7`.
```
"components": [
{
"key": "php_70"
},
```
Related YT: https://tickets.engineyard.com/issue/CC-1049
Adds the ability to select PHP versions, including PHP 7. This is currently behind a feature flag. Please open a Support Ticket to enable it.
Minimal.
Enable nonruby-version-select flag
Create a new PHP environment
Pick PHP 7.0
Boot
Edit `/etc/chef/recipes/cookbooks/php/attributes/php.rb` - replace 'php_7' with 'php_70'
Run chef with 
```
PATH=/usr/local/ey_resin/bin:$PATH /home/ey/bin/chef-solo -j /etc/chef/dna.json -c /etc/chef/solo.rb
```
A) Scenarios: Booting a new environment, adding an instance to the environment
Enable …

Typo fix: use 2 digits for PHP7 version

---

cookbooks/newrelic/providers/default.rb
cookbooks/newrelic/recipes/default.rb
cookbooks/newrelic/resources/default.rb
cookbooks/newrelic/templates/default/newrelic-sysmond.init.erb
cookbooks/newrelic/templates/default/newrelic.cfg.erb
cookbooks/newrelic/templates/default/nrsysmond.cfg.erb

Restart php and nginx after installing New Relic for php only on app
instances
Create newrelic.ini for php 5.6 and 7.0

Add labels to New Relic server monitoring and PHP 7.0 support

---

cookbooks/php/attributes/php.rb

This reverts commit 62c640fc4aad3365169645f6a53053c3e4a01a33 from #70 .
I'm not sure what changed, but dna.json now shows `php_7` not `php_70`. As a result, PHP selection works on gentoo-2016-qa-1.0.32 (before #70) but fails on gentoo-2016-qa-1.0.34 (has PR #70 merged). Reverting 62c640fc4aad3365169645f6a53053c3e4a01a33 should make PHP selection work again.
```
"components": [
{
"key": "php_7"
},
```
Related YT: https://tickets.engineyard.com/issue/CC-1049
Adds the ability to select PHP versions, including PHP 7. This is currently behind a feature flag. Please open a Support Ticket to enable it.
Minimal.
Enable nonruby-version-select flag
Create a new PHP environment
Pick PHP 7.0
Boot
Edit `/etc/chef/recipes/cookbooks/php/attributes/php.rb` - replace 'php_7' with …

Revert "Typo fix: use 2 digits for PHP7 version"

---

cookbooks/sidekiq/attributes/default.rb
cookbooks/sidekiq/recipes/cleanup.rb
cookbooks/sidekiq/recipes/setup.rb
cookbooks/sidekiq/templates/default/sidekiq.monitrc.erb

Unlike #62 and #63, this is a breaking change. It changes the attribute `sidekiq['workers']` from an integer to an array of hashes.
This allows configuring sidekiq workers independently — so that different workers can service different queues, operate with different levels of concurrency or with different memory limits.

Allowed configuring workers independently

---

cookbooks/sidekiq/files/default/sidekiq

[To use Reliable Fetch (a feature of Sidekiq Pro) you're required to pass a worker ID to each worker](https://github.com/mperham/sidekiq/wiki/Reliability#using-reliable_fetch)

Modified /engineyard/bin/sidekiq to pass worker ID to support reliable fetch

---

cookbooks/openssl/attributes/openssl.rb

Upgrade to version of OpenSSL 1.0.2j
Provides OpenSSL 1.0.2 with patches for  CVE-2016-2177, CVE-2016-2178, CVE-2016-2181, CVE-2016-2179, CVE-2016-6302, CVE-2016-8610
Low: Updated OpenSSL version
OpenSSL
Package testing was performed by Distribution team. Also verified that code change caused 1.0.2j to be used.
1. Boot environment on stable stack.
2. Ensure chef runs to completion successfully and app deploys and runs as expected
3. Configure app to use SSL certificate and apply changes
4. Confirm 1.0.2d as the openssl version with openssl version 
5. Confirm the installed version of openssl according to eix openssl  is '1.0.2d'
6. Upgrade to target stack, and click apply
7. Verify 1.0.2j as the openssl version with openssl version 
8. Verify the app is reachable via https and runs as …

CC-1084 Updated OpenSSL to 1.0.2j

---

cookbooks/delayed_job4/templates/default/dj.erb

FIXED: Stopping DJ ends up killing the parent process, which is monit. 
Custom chef: Fixes an issue with the DelayedJob4 custom chef recipe.
Low. Only the DelayedJob4 custom chef recipe was updated.
DelayedJob4 custom chef recipe
A. Replicate the error
1. Add an application: https://github.com/radamanthus/noisy_dj and an environment running the stable stack 
2. Modify the delayed_job4 recipe to use a lower memory limit
3. Upload the recipes
4. Boot the environment
5. Get the PID of the monit process
6. Generate 100 jobs: cd /data/noisy_dj/current; ECHO_JOB_COUNT=100 bundle exec rake echo:generate
7. Wait 1 minute
8. Get the PID of the monit process. Verify that it's not the same as the PID obtained in step 5.
B. Verify the fix
9. Upgrade to the target stack
10. Get the …

[CC-1090] Fix dj.erb

---

cookbooks/sidekiq/templates/default/sidekiq.yml.erb

Reverts engineyard/ey-cookbooks-stable-v5#62

Revert "Modified sidekiq.yml to produce valid YML if a queue name contains punctuation (like ":")"

---

cookbooks/collectd/files/default/check_health_for
cookbooks/mysql/templates/default/check_mysql.sh.erb
cookbooks/postgresql/templates/default/check_postgres_wrapper.sh.erb

NOTE: QA for this should be handled by one of the non-Erik DBAs.
-------------
Fix incorrect comparison operator used in collectd check scripts
-------------
Fix incorrect comparison operator used in collectd check scripts that prevented some OKAY alerts from being delivered.
Estimated risk
-------------
Low
-------------
$ git diff --name-only master
cookbooks/collectd/files/default/check_health_for
cookbooks/mysql/templates/default/check_mysql.sh.erb
cookbooks/postgresql/templates/default/check_postgres_wrapper.sh.erb
-------------
Confirm issue:
1. Boot stable-v5 env. A solo env is fine.
2. Stop the db on it.
3. Confirm failure alerts go out for everything except maybe the checkpoint …

Fix incorrect comparison operator used in collectd check scripts

---

cookbooks/mysql/attributes/version.rb
cookbooks/mysql/recipes/install.rb
cookbooks/mysql/recipes/master.rb
cookbooks/mysql/templates/default/my.conf.erb

--------------
Adds MySQL Community 5.5.49 to the Stable-v5 Stack. This build is intended for use by customers needing a gradual migration step to the v5 stack and will remain behind a limited access flag.
--------------
Adds MySQL Community 5.5.49 behind a limited access flag.
Estimated risk
--------------
Low
- An Engine Yard support Engineer must enable this feature for it to be used ensuring it will only be used in limited cases.
--------------
cookbooks/mysql/attributes/version.rb
cookbooks/mysql/recipes/install.rb
cookbooks/mysql/recipes/master.rb
cookbooks/mysql/templates/default/my.conf.erb
--------------
Under a testing stack on one of our platform …

Cc 1069 - Add MySQL 5.5.49 to Stable-v5 (limited access)

---

cookbooks/redis/recipes/default.rb
cookbooks/sysctl/recipes/tune.rb
cookbooks/sysctl/recipes/tune_large_db.rb

-------------
Disable transparent_hugepages and adjust vm dirty rations on large dbs
transparent_hugepages can devastate performance on for database workloads
but is only present on larger instances.  This disables it for database
(and solo) instances when present and also does some vm dirty flushing
tweaking to start background flushing sooner.
-------------
Disable transparent_hugepages and adjust kernel vm dirty ratios and rates
on database instances when present.
Estimated risk
-------------
Low.
-------------
$ git diff --name-only next-release
cookbooks/redis/recipes/default.rb
cookbooks/sysctl/recipes/tune.rb
cookbooks/sysctl/recipes/tune_large_db.rb
-------------
Boot both a solo …

Disable Transparent Huge Pages on large db & redis instances

---

examples/logrotate/README.md
examples/logrotate/cookbooks/custom-logrotate/README.md
examples/logrotate/cookbooks/custom-logrotate/metadata.rb
examples/logrotate/cookbooks/custom-logrotate/recipes/default.rb
examples/logrotate/cookbooks/ey-custom/metadata.rb
examples/logrotate/cookbooks/ey-custom/recipes/after-main.rb

Note: custom-logrotate in examples/ does not wrap a recipe under cookbooks/. Instead it just calls the `logrotate` resource defined in the main `logrotate` recipe.
* Generates a file under /etc/logrotate.d/.
* Most options are just logrotate options (see `man logrotate`) but one option, `enable`, will create or delete the config file under /etc/logrotate.d/ depending on the value.

Custom logrotate (calls logrotate resource defined by main logrotate cookbook)

---

cookbooks/redis/recipes/default.rb

The block in the default recipe that generates `redis.yml` and
the /etc/hosts changes did not previously consider the value of
`node['redis']['utility_name']`, so environments that named their
redis utility instances something other than "redis" were not
getting the app and hosts config.

Honor redis utility name for redis.yml generation

---

cookbooks/delayed_job4/attributes/default.rb
cookbooks/delayed_job4/recipes/default.rb
cookbooks/delayed_job4/templates/default/dj.monitrc.erb
examples/delayed_job4/cookbooks/custom-delayed_job4/README.md
examples/delayed_job4/cookbooks/custom-delayed_job4/attributes/default.rb

-------------
This change makes the DJ worker memory limit specified in the monit control file customizable through the attributes in the wrapper cookbook.
This was a customer request: "Could you consider a change to the DJ custom-DJ recipes so we could pass in the memory limit size for monit."
-------------
Makes DJ worker memory limit customizable through custom-delayed_job4/attributes/default.rb.
Estimated risk
-------------
Low - only applies to those enabling the DJ custom chef recipe, and the change is fairly simple.
How to Test
-------------
Use delayed_job4 custom chef recipe. Check monit control file in /etc/monit.d/delayed_job*.monitrc. Memory limit before restarting worker is 300MB.
Use updated delayed_job4 custom chef recipe …

Add worker memory limit setting for delayed job.

---

cookbooks/ey-core/recipes/default.rb
cookbooks/ey-hosts/README.md
cookbooks/ey-hosts/metadata.rb
cookbooks/ey-hosts/recipes/default.rb
cookbooks/ey-hosts/templates/default/ey_hosts.erb

--------------
Adds EY-HOSTS section to /etc/hosts file providing a friendly alias to the internal ip address of each host in the environment.
--------------
Adds /etc/hosts entries for the private IP of each instance in the environment
Estimated risk
--------------
Low
- Adds functionality that does not exist currently to a rarely leveraged configuration file.
--------------
cookbooks/ey-core/recipes/default.rb
cookbooks/ey-hosts/README.md
cookbooks/ey-hosts/metadata.rb
cookbooks/ey-hosts/recipes/default.rb
cookbooks/ey-hosts/templates/default/ey_hosts.erb
Example
--------------
```
#---EY-HOSTS-START
10.203.197.207        ey-app-master
10.230.182.98        ey-app-slave-0 …
```

Add EY-HOSTS section to /etc/hosts

---

cookbooks/mysql/templates/default/my.conf.erb

--------------
Rollup of multiple database changes
MySQL:
- `table_open_cache`
- MySQL 5.5 sets a default of 2000 in the mysql config file
- Uses build default for MySQL 5.6+
- `open_files_limit`
- Sets to a default of 65,535 for all versions.
- `show_old_temporals`
- MySQL 5.6 only, sets to true.
--------------
- Adjusts the MySQL default settings for `table_open_cache`, `open_files_limit`, and `show_old_temporals`.
Estimated risk
--------------
Low
- The MySQL configuration changes don't change the running server and only apply after a restart, the changes are designed to improve reliability.
--------------
cookbooks/mysql/templates/default/my.conf.erb …

updating default mysql configuration to adjust open_files_limit, table_open_cache, and show_old_temporals

---

cookbooks/ey-lib/libraries/ey-application.rb
cookbooks/ey-lib/libraries/metadata.rb

Bugfix to make metadata fetching work on v5. v5 uses Hash instead of Mash in v4, so keys have to be strings, not symbols.
Fixed a bug wherein metadata fails to load properly.
High. All code that fetches metadata is affected.
Main chef cookbook
Test on Unicorn and Passenger environments
Boot a stable-v5.0.20 environment
Set the metadata at the account, application, environment, and app_deployment level. On all cases the metadata should be picked up and applied to the worker count configuration.
Set the metadata worker count to 1
Click Apply
Verify that the metadata is still at the default (see https://support.cloud.engineyard.com/hc/en-us/articles/205407758-Worker-Allocation-on-Engine-Yard-Cloud for the default worker counts)
Upgrade to the QA stack, click Apply
Verify …

[CC-1059] Stringify the key when fetching metadata

---

cookbooks/memcached/README.md
cookbooks/memcached/attributes/default.rb
cookbooks/memcached/metadata.rb
cookbooks/memcached/recipes/configure.rb
cookbooks/memcached/recipes/default.rb
cookbooks/memcached/recipes/install.rb
cookbooks/memcached/recipes/install_from_package.rb
cookbooks/memcached/recipes/install_from_source.rb
cookbooks/memcached/templates/default/memcached.erb
cookbooks/memcached/templates/default/memcached.monitrc
cookbooks/memcached/templates/default/memcached.yml.erb
examples/memcached/README.md
examples/memcached/cookbooks/custom-memcached/README.md
examples/memcached/cookbooks/custom-memcached/attributes/default.rb
examples/memcached/cookbooks/custom-memcached/metadata.rb
examples/memcached/cookbooks/custom-memcached/recipes/default.rb
examples/memcached/cookbooks/ey-custom/metadata.rb
examples/memcached/cookbooks/ey-custom/recipes/after-main.rb

Adds the memcached custom recipe. 
The previous recipe was just a stub. This actually installs memcahced, but it has to be enabled by setting `perform_install` to true in `custom-memcached/attributes/default.rb`.
Adds the memcached custom recipe.
High. 
Our platform includes memcached in the list of recipes that should be run by default (a legacy from the V4 stack). Breakage on this recipe will cause main chef to fail for all chef runs on V5. To mitigate this, the recipe has an attribute `perform_install` and this is disabled by default.
memcached custom chef recipe
Run the test cases in examples/redis/cookbooks/custom-memcached/README.md

Add memcached recipe

---

cookbooks/rails_secrets/README.md
cookbooks/rails_secrets/metadata.rb
cookbooks/rails_secrets/recipes/default.rb
examples/rails_secrets/README.md
examples/rails_secrets/cookbooks/custom-rails_secrets/README.md
examples/rails_secrets/cookbooks/custom-rails_secrets/metadata.rb
examples/rails_secrets/cookbooks/custom-rails_secrets/recipes/default.rb
examples/rails_secrets/cookbooks/custom-rails_secrets/templates/default/secrets.yml.todo.erb
examples/rails_secrets/cookbooks/ey-custom/metadata.rb
examples/rails_secrets/cookbooks/ey-custom/recipes/after-main.rb

Adds the rails-secrets custom chef recipe
Adds the rails-secrets custom chef recipe
Low. Main chef recipes weren’t updated.
Custom chef recipes
A. Test on a solo Rails environment 
Enable the custom-rails-secrets recipe
Upload chef and click Apply
Verify that there were no chef errors
Deploy and verify that the application runs after the deploy
Verify that /data/appname/shared/config/secrets.yml has the same content as recipe_home/cookbooks/custom-rails-secrets/templates/default/secrets.yml.appname.erb
B. Test on a cluster Rails environment
Enable the custom-rails-secrets recipe
Upload chef and click Apply
On all instances, Verify that there were no chef errors
Deploy and verify that the application runs after the deploy
On app and util instances, verify that …

Add the rails-secrets custom chef recipe

---

cookbooks/delayed_job4/attributes/default.rb

-------------
This change adds default values for worker count for additional instance types.
-------------
Added default worker count for more instance types in Delayed Job custom chef recipe.
Estimated risk
-------------
Low - only applies to those enabling the DJ custom chef recipe, and the change is fairly simple.
How to Test
-------------
Use delayed_job4 custom chef recipe. Make sure `is_dj_instance` attribute uses default value that also sets up DJ in utility instances named "delayed_job". Try adding utility instances named "delayed_job" with various instance types (t2, r3, r4) and compare to the default values in delayed_job4/attributes/default.rb.

DJ: Add default worker count for more instance types.

---

cookbooks/sidekiq/attributes/default.rb
cookbooks/sidekiq/recipes/setup.rb
examples/sidekiq/cookbooks/custom-sidekiq/README.md
examples/sidekiq/cookbooks/custom-sidekiq/attributes/default.rb

-------------
This change makes the Sidekiq worker memory limit specified in the monit control file customizable through the attributes in the wrapper cookbook.
-------------
Makes Sidekiq worker memory limit customizable (through custom-sidekiq/attributes/default.rb).
Estimated risk
-------------
Low - only applies to those enabling the Sidekiq custom chef recipe, and the change is fairly simple.
How to Test
-------------
Use sidekiq custom chef recipe. Check monit control file in /etc/monit.d/sidekiq*.monitrc. Memory limit before restarting worker is 400MB.
Use updated sidekiq custom chef recipe without customizing custom-sidekiq/attributes/default.rb. Results should be the same as before. Memory limit is still at 400MB.
Uncomment the …

Add worker memory limit setting for Sidekiq.

---

cookbooks/postgresql/recipes/server_configure.rb
cookbooks/postgresql/templates/default/postgresql.conf.erb

-------------
Fix incorrectly setting postgres temp_tablespaces
-------------
Fix incorrectly setting postgres temp_tablespaces
Estimated risk
-------------
Low
-------------
$ git diff --name-only master 
cookbooks/postgresql/recipes/server_configure.rb
cookbooks/postgresql/templates/default/postgresql.conf.erb
-------------
* Apply cookbooks w/ fix on Postgres env w/ db_master & db_slave.
* Log into both servers and verify that this returns a blank string:
`psql -t -c"SHOW temp_tablespaces;"`
-------------
Same as testing above.

Fix incorrectly setting postgres temp_tablespaces

---

cookbooks/nginx/definitions/nginx_vhost.rb

Bugfix to make https for puma work properly
Fixed a bug wherein chef fails to complete with puma and an ssl assigned
Low
Nginx Cookbook definition
1. Test on Puma environments
2.  Boot a stable stack environment. Verify chef completes
3.  Set the application to use an ssl certificate.
4.  Run another Chef to put the ssl in place.
5.  Upgrade to new stack
6. Verify chef completes correctly.

CC-1114 Define https port

---

cookbooks/passenger5/templates/default/nginx_app.conf.erb

--------------
Fixed a passenger 5 bug caused by multiple domain names in the dashboard not being filtered properly in a configuration file.
--------------
Fixed a passenger 5 bug caused by multiple domain names
Estimated risk
--------------
Low
- minor changes that only affects the passenger 5 template
--------------
cookbooks/passenger5/templates/default/nginx_app.conf.erb
--------------
under a v5 cluster with the issue that had previously failed due to the bug added the code and the issue was resolved.
--------------
1.  Add multiple domain names to the applicaton under edit application.
2.  Boot environment
3.  The initial chef run …

[CC-1125] Passenger 5 will fail if more than one domain set in the application

---

cookbooks/php/attributes/php.rb

**Description of your patch**
Chef component for php 7.1 version selection, once the option is available via the dashboard
**Recommended Release Notes**
back end support for PHP 7.1 version selection
**Estimated risk**
Low
**Components involved**
php cookbook attributes file
**Description of testing done**
**QA Instructions**
Bring up a php environment with the updated attributes file
modify the attribute['dna']['engineyard']['environment'][''
components'] php key value to php_71
Run chef locally with PATH=/usr/local/ey_resin/bin ey-enzyme --cached --verbose --chef-bin /usr/local/ey_resin/bin/chef-solo
confirm version is 7.1.0 with php -v and php-fpm -v

CC-1109 added support for php 7.1

---

cookbooks/sidekiq/templates/default/sidekiq.yml.erb

Addresses issue @crigor noticed with #62

Modified sidekiq.yml to produce valid YML if a queue name contains punctuation (like ":")

---

cookbooks/redis/recipes/install.rb

`node['dna']['name'] == node['redis']['slave_name']` evaluates to true on a solo instance

Fix redis recipe bug when setting up on solo instance

---

README.md
docs/how_it_works.md

The original README.md was moved to docs/how_it_works.md

Replace README.md with usage instructions

---

examples/resque_scheduler/cookbooks/custom-redis/README.md
examples/resque_scheduler/cookbooks/custom-redis/attributes/default.rb
examples/resque_scheduler/cookbooks/custom-redis/metadata.rb
examples/resque_scheduler/cookbooks/custom-redis/recipes/default.rb
examples/resque_scheduler/cookbooks/ey-custom/metadata.rb
examples/resque_scheduler/cookbooks/ey-custom/recipes/after-main.rb

We need another PR to update the README - add a section about how to modify the Redis recipe for cases where Resque and Redis should be installed on the same utility instance. We'll do that in another PR to avoid merge conflicts with #149

Remove custom-redis from resque-scheduler recipe

---

custom-cookbooks/redis/cookbooks/custom-redis/README.md
custom-cookbooks/resque/cookbooks/custom-redis/README.md
custom-cookbooks/resque/cookbooks/custom-redis/attributes/default.rb
custom-cookbooks/resque/cookbooks/custom-redis/metadata.rb
custom-cookbooks/resque/cookbooks/custom-redis/recipes/default.rb
custom-cookbooks/resque/cookbooks/custom-resque/README.md
custom-cookbooks/resque/cookbooks/ey-custom/metadata.rb
custom-cookbooks/resque/cookbooks/ey-custom/recipes/after-main.rb
custom-cookbooks/resque_scheduler/cookbooks/custom-redis/README.md
custom-cookbooks/resque_scheduler/cookbooks/custom-redis/attributes/default.rb
custom-cookbooks/resque_scheduler/cookbooks/custom-redis/metadata.rb
custom-cookbooks/resque_scheduler/cookbooks/custom-redis/recipes/default.rb
custom-cookbooks/resque_scheduler/cookbooks/custom-resque_scheduler/README.md

..and added pointers to the Redis recipe
Bonus README update included instructions on how to run Redis and Resque/Sidekiq on the same instance.

Remove custom-redis from resque-scheduler and resque recipes

---

cookbooks/solr/attributes/default.rb
cookbooks/solr/recipes/install.rb
custom-cookbooks/solr/cookbooks/custom-solr/attributes/default.rb

Updates the Solr recipe to use the latest IcedTea JDK that includes patches for recent vulnerabilities.
Updates the Solr recipe to use the latest IcedTea JDK that includes patches for recent vulnerabilities.
Low. 
Solr custom chef recipe
Install Solr on an environment. Either Solo or cluster is OK. Verify that there were no chef errors encountered, and that Solr is running after the chef run.

Update Solr to use latest JDK

---

cookbooks/elasticsearch/attributes/default.rb
cookbooks/elasticsearch/recipes/install.rb
custom-cookbooks/elasticsearch/cookbooks/custom-elasticsearch/attributes/default.rb

Updates the Elasticsearch recipe to use the latest IcedTea JDK that includes patches for recent vulnerabilities.
Updates the Elasticsearch recipe to use the latest IcedTea JDK that includes patches for recent vulnerabilities.
Low. 
Elasticsearch custom chef recipe
Install Elasticsearch on an environment. Either Solo or cluster is OK. Verify that there were no chef errors encountered, and that Elasticsearch is running after the chef run.

Update Elasticsearch to use latest JDK

---

cookbooks/sidekiq/files/default/sidekiq

Fixes the Sidekiq recipe to address issue #154
Updates the Solr recipe to use the latest IcedTea JDK that includes patches for recent vulnerabilities.
Low. 
Sidekiq custom chef recipe
1. Verify the error.
Boot a stable-v5.3.0.22 environment running rails_activejob_example. Use the sidekiq recipe to run sidekiq on the environment
Deploy the sidekiq-stdout branch of rails_activejob_example (https://github.com/engineyard/rails_activejob_example/tree/sidekiq-stdout) on an environment
Generate jobs
Verify if there are Broken Pipe errors in the sidekiq log
2. Upgrade to the QA stack
Generate jobs again
Check <Rails.root>/tmp/echo.output to verify that the jobs ran successfully
Verify that there are no Broken Pipe errors in the sidekiq log

Fix sidekiq start command

---

examples/README.md

We renamed examples/ to custom-cookbooks. Add a pointer to the new location.

Add examples/ placeholder

---

cookbooks/mysql/attributes/version.rb
cookbooks/mysql/recipes/default.rb
cookbooks/mysql/recipes/master.rb
cookbooks/mysql/recipes/slave.rb

--------------
Corrects an issue with the identification of the full mysql version on the Stable-v4 stack that prevents older versions from starting from a snapshot.
--------------
V4
- Corrects an issue where MySQL versions lower than 5.6.24 won't start when booting from snapshot due to show_old_temporals in the config file.
V5
- Corrects the chef process identifying the full local MySQL version, and moves the EBS mount process earlier in the MySQL cookbook.
Estimated risk
--------------
Low
- This is a bugfix release for Stable-v4
- This fixes a currently 0 impact bug in Stable-v5
--------------
cookbooks/mysql/attributes/version.rb
cookbooks/mysql/recipes/default.rb …

change from compile time to run time evaluation of installed mysql version

---

cookbooks/haproxy/attributes/haproxy.rb
cookbooks/lb/attributes/haproxy.rb

-------------
Updates haproxy to version 1.6.5 from 1.5.14.
-------------
Update haproxy to version 1.6
Estimated risk
-------------
Medium
-------------
$ git diff --name-only next-release
cookbooks/haproxy/attributes/haproxy.rb
cookbooks/lb/attributes/haproxy.rb
-------------
* Verify haproxy is version 1.5.14 with `eix haproxy`
* Update cookbooks
* Verify chef completes without issue
* Verify haproxy is now version 1.6.5 with `eix haproxy`
-------------
Same as testing above.

[CC-1126] Update haproxy to 1.6 from 1.5 properly

---

cookbooks/passenger5/files/default/passenger_killer
cookbooks/passenger5/files/default/passenger_monitor
cookbooks/passenger5/recipes/monitoring.rb

-------------
The Passenger monitoring recipe is being skipped because it uses the old v4 way of fetching data. This change fixes that, and also updates other node/dna references.
-------------
Sets up cron jobs for Passenger monitoring that automatically kills worker above a memory threshold.
Estimated risk
-------------
Medium. While it only affects v5/passenger5 environments (around 49 active environments of 33 customers), passenger monitoring kills workers so when enabled, it can potentially interrupt some requests.
How to Test
-------------
Select Passenger 5 as your environment's Application Server Stack. You may need to enable passenger5 feature if it's not showing up in the dropdown.
Once the environment is booted, in your app …

Enable Passenger Monitoring

---

custom-cookbooks/memcached/cookbooks/custom-memcached/README.md

Calling the documented commands ends with:
```
The application encountered the following error:
invalid option: --path=./cookbooks
```

Remove `--path` from memcache README

---

cookbooks/ey-lib/libraries/ey-environment.rb

Upgrade Ruby 2.2.x to 2.2.6 and 2.3.x to 2.3.3.
Upgrade Ruby 2.2.x to 2.2.6 and 2.3.x to 2.3.3.  
Note: currently running Ruby processes will continue to run on the existing version of ruby.  To update these processes, redeploy your app, and restart any background ruby processes.  If using passenger, run `/etc/init.d/nginx upgrade` on each app instance to restart passenger and its workers on the new version.
Low
Ruby
Package validated by distribution team
2. Ensure chef completes successfully and app deploys and runs as expected
3. Upgrade to target stack
4. Verify chef run completes successfully
5. Verify the correct version of ruby is installed: `ruby -v` should return 2.2.6
6. Deploy the application
7. Verify app deploys and runs as expected, with …

[CC-1138] Update to Ruby 2.2.6 and Ruby 2.3.3

---

cookbooks/node/attributes/node.rb

- Add availability of 4.7.3 and 6.9.5
- Set default for NodeJS 4 to 4.7.3
- Set default for NodeJS 6 to 6.9.5
Add availability of NodeJS version 4.7.3 and 6.9.5
Set default for NodeJS 4 to version 4.7.3
Set default for NodeJS 6 to version 6.9.5
Note: currently running NodeJS processes will continue to run on the existing version of ruby. To update these processes, redeploy your app.
Low
NodeJS.  It affects assets compilation for Ruby and PHP apps as well.
Package validated by distribution team
Testing will only be done on NodeJS apps.  
The version of NodeJS used for assets compilation on Ruby apps is generally specified by the customer on the app's `package.json` file, thus under their control.
1. Create an NodeJS app (can be our demo one).
2. Build environment on stable stack.
3. Leave …

Bump version 4 and 6 of NodeJS

---

cookbooks/elixir/recipes/configure.rb
cookbooks/elixir/recipes/nginx.rb
cookbooks/elixir/templates/default/phoenix.monitrc.erb
cookbooks/elixir/templates/default/prod.secret.exs.erb

-------------
The `elixir_app_name` directive is not properly set for Elixir applications, and this change fixes that.
-------------
Sets the `elixir_app_name` in prod.secret.exs and monit configurations for Elixir applications.
Estimated risk
-------------
Low. It only affects v5 elixir environments 
How to Test
-------------
Setup an Elixir environment on v5. 
Keep the Application Name in the Edit Application page blank. 
Verify that the monit configuration is the same.
Add a different Elixir Application Name
Run Chef
Verify that the /data/<appname>/shared/config/prod.secret.exs only has the elixir_app_name present and that the monitrc file has both app.name and elixir_app_name present

Added Elixir App Name for configuration generation

---

cookbooks/pm2/recipes/default.rb

-------------
PM2 gets the wrong worker count on initial boot chef run, and fails to take into account the swap. This change uses Chef's lazy evaluation feature to only calculate the pool size after swap is configured.
-------------
Fix PM2 worker count on initial boot chef run.
Estimated risk
-------------
Low. PM2 is not yet GA.
How to Test
-------------
Refer to our Worker Allocation calculator to figure out the expected number of workers:
https://support.cloud.engineyard.com/hc/en-us/articles/205407758-Worker-Allocation-on-Engine-Yard-Cloud
Make sure that node_pm2 feature is enabled for your account. Boot up a Node.js environment with your selected instance type. Select "Node.js PM2" for the Application Server Stack. Using the QA …

CC-1147: Fix PM2 worker count on initial boot chef run.

---

cookbooks/ey-lib/libraries/ey-environment.rb
cookbooks/ruby/recipes/ruby.rb

Add Ruby 2.4.0
Addition of Ruby 2.4.0
Low
dnapi.rb and ruby cookbook
Followed QA instructions
- Boot environment on stable stack
- Add "ruby_version":"2.4.0" to dna metadata of environment
- Verify chef fails
- Update to target stack
- Verify chef finishes without error
- Verify Ruby version is `2.4.0` with ruby -v on the instance

CC-1143 Add Ruby 2.4.0 to v5

---

cookbooks/node/recipes/node_app.rb

-------------
The `server_name` directive is not properly set for Node.js applications, and this change fixes that.
-------------
Sets the `server_name` in Nginx configuration for Node.js applications.
Estimated risk
-------------
Low. It only affects v5 node environments that set the domain_name. There's only 10 at this time:
```
(Environment.all(:release_label.like => 'stable-v5-3.0%') & Environment.all(Environment.app_deployments.domain_name.not => "_") & Environment.all(Environment.apps.app_type_id => "nodejs")).select{|e| e.instances.size > 0 }.size
```
How to Test
-------------
Setup a Node.js environment on v5. Test this change for each of these Application Server Stacks:
* Nginx (Recommended)
* Node.js PM2
Keep the Domain Name in …

Fix Nginx server_name for node apps

---

cookbooks/mysql/templates/default/check_mysql.sh.erb
cookbooks/postgresql/templates/default/check_postgres_wrapper.sh.erb

-------------
Don't alert for database replication while blocking backups are running.
-------------
Don't alert for database replication while blocking backups are running.
Estimated risk
-------------
Low
-------------
$ git diff --name-only next-release
cookbooks/mysql/templates/default/check_mysql.sh.erb
cookbooks/postgresql/templates/default/check_postgres_wrapper.sh.erb
-------------
Have DBAs test.
-------------
Have DBAs test.

Don't alert for database replication while blocking backups are running.

---

cookbooks/pm2/recipes/default.rb

-------------
CC-1144 originally reports that pm2 is not started by the right user. But instead of fixing the openrc script, we have to remove the entire script because it duplicates the functionality of the pm2 monit script that already ensures that pm2 is resurrected.
-------------
Remove PM2 openrc script to avoid duplicate functionality with pm2 monitrc script that resurrects PM2.
Estimated risk
-------------
Low. PM2 is not yet GA and only being tested by a couple of customers.
How to Test
-------------
First, make sure that node_pm2 feature is enabled for your account. Setup an environment and select "Node.js PM2" for the Application Server Stack. If you use stable-v5-3.0.24, you can still see the pm2 service added to runlevel …

Remove PM2's openrc script as monit already handles PM2 resurrect

---

cookbooks/fail2ban/recipes/service.rb

Do not start the service, otherwise there might arise a race condition wherein chef tries to start the service and monit already started it so chef fails.

fail2ban: let monit start the service

---

cookbooks/postgresql/recipes/server_configure.rb

--------------
Adds custom VPC CIDR support to Postgres Host Based Authentication.
--------------
Adds support for custom VPCs to pg_hba.conf
Estimated risk
--------------
Low
- Adds better intelligency about how CIDR is set to the Postgres recipes.
- Recommended procedure for databases is to always test new releases in a non-Production environment before upgrading Production.
--------------
cookbooks/postgresql/recipes/server_configure.rb
--------------
- Enable the `VPCs` feature for the account
- In Tools->Networks add a VPC if one doesn't already exist using a 192.168.0.0/16 or 172.16.0.0/12 CIDR
- Boot the environment as a cluster
- …

Add support for additional internal netmasks for VPC support.

---

cookbooks/postgresql/attributes/version.rb
cookbooks/postgresql/recipes/server_install.rb

--------------
Updates Postgresql-server to 9.4.11.
--------------
Adds support PostgreSQL 9.4.11. See our [Upgrade Procedures](https://support.cloud.engineyard.com/hc/en-us/articles/205408178-Database-Version-Upgrade-Policies) for additional details about applying this update.
Estimated risk
--------------
Low
- Customers need to take additional steps to apply this update or must have opted in to automatic updates.
- Recommended procedure for databases is to always test new releases in a non-Production environment before upgrading Production.
--------------
cookbooks/postgresql/attributes/version.rb
cookbooks/postgresql/recipes/server_install.rb
-------------- …

add support for Postgres 9.4.11

---

cookbooks/ey-lib/libraries/ey-environment.rb

Add Ruby 2.4.1
Addition of Ruby 2.4.1
Low
dnapi.rb
Followed QA instructions
- Boot environment on stable stack
- Add "ruby_version":"2.4.1" to dna metadata of environment
- Verify chef fails
- Update to target stack
- Verify chef finishes without error
- Verify Ruby version is `2.4.1` with ruby -v on the instance

CC-1148 Updated 2.4.0 to 2.4.1

---

cookbooks/mysql/attributes/version.rb
cookbooks/mysql/recipes/install.rb
cookbooks/mysql/templates/default/my.conf.erb
cookbooks/postgresql/attributes/version.rb
cookbooks/postgresql/recipes/server_install.rb

--------------
Updates Percona-Server to 5.6.35 and 5.7.17 and updates PostgreSQL to 9.5.6.
--------------
Adds Percona-Server 5.6.35 and 5.5.54; adds PostgreSQL 9.5.6. See our [Upgrade Procedures](https://support.cloud.engineyard.com/hc/en-us/articles/205408178-Database-Version-Upgrade-Policies) for additional details about applying these updates.
Estimated risk
--------------
Low
- Customers need to take additional steps to apply this update or must have opted in to automatic updates.
- Recommended procedure for databases is to always test new releases in a non-Production environment before upgrading Production.
--------------
cookbooks/mysql/attributes/version.rb …

Updates Percona-Server to 5.6.35 and 5.7.17 and updates PostgreSQL to 9.5.6.

---

cookbooks/passenger5/files/default/passenger_monitor

Fixes the test for detecting orphan passenger processes
Fixes the test for detecting orphan passenger processes
Low
Passenger chef recipe
Boot an Nginx/Passenger5 environment under the latest stable-v5 stack
Run `tail -f /var/log/syslog | grep illing` on the solo/app instances. You should see a new entry every minute
Upgrade the environment to the QA stack
Verify that the chef run was successful
Run `tail -f /var/log/syslog | grep illing` on the solo/app instances. You should no longer see a new entry every minute

CC-1161: Fix test for detecting orphan passenger processes

---

cookbooks/passenger5/files/default/env.custom
cookbooks/passenger5/recipes/install.rb
cookbooks/passenger5/templates/default/app_control.erb

Adds passenger 5 to have env.custom support
Creates and includes env.custom support for passenger 5
Low
Passenger 5 recipe
Solo, new environment
1. Boot instance on old stack with passenger 5
2. Verify boot of instance
3. Verify chef runs 
4. Verify deploy and application start
5. Verify no env.custom exists in /data/appname/shared/config/env.custom 
6. Upgrade to new stack
7. Verify env.custom  now exists 
8. Run a deploy and verify application deploys and functions

CC-1058 Add environment variable support for passenger 5 to be read

---

cookbooks/memcached/templates/default/memcached.yml.erb

-------------
This change adds a servers list under the defaults section of memcached.yml.
In v4 main chef, we provide the list of memcached servers under the defaults section of the memcached.yml. In v4 custom chef, servers are listed under the framework env section. In v5, we followed the v4 custom chef and listed it under the framework env section too. But for customers expecting the old structure from v4 main chef, it broke their memcached setup. To make migrating from v4 to v5 easier, we should provide the list of servers on both defaults and framework env sections.
-------------
Add list of memcached servers under the defaults section of memcached.yml.
Estimated risk
-------------
Low. Memcached is not enabled by default. And for …

CC-1162: In memcached.yml, add servers list under defaults section

---

cookbooks/env_vars/README.md
cookbooks/env_vars/attributes/default.rb
cookbooks/env_vars/metadata.rb
cookbooks/env_vars/recipes/default.rb
custom-cookbooks/env_vars/cookbooks/custom-env_vars/README.md
custom-cookbooks/env_vars/cookbooks/custom-env_vars/attributes/default.rb
custom-cookbooks/env_vars/cookbooks/custom-env_vars/files/default/env.custom
custom-cookbooks/env_vars/cookbooks/custom-env_vars/metadata.rb
custom-cookbooks/env_vars/cookbooks/custom-env_vars/recipes/default.rb
custom-cookbooks/env_vars/cookbooks/ey-custom/metadata.rb
custom-cookbooks/env_vars/cookbooks/ey-custom/recipes/after-main.rb

Adds the env_vars custom chef recipe
Adds the env_vars custom chef recipe
Low. 
Custom chef recipes
Test on a Passenger environment for the todo application
Add env_vars to the custom chef recipes
Boot the environment on the QA stack
Upload and run the recipes
Verify that the chef run was successful
Add this line to custom-env_vars/files/default/env.custom then upload and apply:
```
export ENV_VAR_TEST=YEHEY
```
Deploy the env_vars branch
Open the todo app home page. You should see this text:
ENV_VAR_TEST: YEHEY

Add env_vars custom chef recipe

---

cookbooks/timezones/README.md
cookbooks/timezones/recipes/default.rb

--------------
Adds support for timezones in the DNA set at the environment level.
--------------
Adds environment level timezone controls to cookbooks.
Estimated risk
--------------
Low
- Nothing is changed if the timezone is unrecognized or not present.
- Based on the existing custom chef cookbooks that are currently used by customers.
--------------
cookbooks/timezones/README.md
cookbooks/timezones/recipes/default.rb
--------------
Under the 12.11 stack
- Provisioned a solo using the updated stack
- Verified cookbooks completed successfully
- Verified the current timezone with `ls -la /etc/localtime` showed a symlink to `/usr/share/zoneinfo/UTC`
- …

Add support for pending environment timezone feature.

---

cookbooks/papertrail/attributes/default.rb

-------------
The misplaced comma in papertrail/attributes/default.rb is causing the papertrail recipe to add an incorrect entry to /etc/portage/package.keywords/local file:
```
=app-admin/syslog-ng-["3.7.3", "v0.16"]
```
This change simply removes the comma.
-------------
Removes a misplaced comma on the syslog_ng version line in the papertrail attributes file.
Estimated risk
-------------
Low. Papertrail is not enabled by default. Customers who have enabled it have the incorrect behavior that this change fixes.
How to Test
-------------
Prepare a v5 environment.
Enable the papertrail recipe. See:
https://github.com/engineyard/ey-cookbooks-stable-v5/tree/next-release/custom-cookbooks/papertrail
Upload recipes to your environment and …

CC-1177: Remove misplaced comma in papertrail attributes.

---

cookbooks/ey-hosts/recipes/default.rb
cookbooks/ey-hosts/templates/default/ey_hosts.erb

--------------
Corrects EY-HOSTS section skip reporting against hosts for which an IP address cannot be resolved. Currently can happen when RDS replica hosts are removed from a database service (they aren't currently removed from DNA Triage-9440)
--------------
Adjusts ey-hosts generation to only include hosts if their IP can be resolved at runtime
Estimated risk
--------------
Low
- Improves resiliency for situations where a hostname cannot be resolved.
--------------
cookbooks/ey-hosts/recipes/default.rb
cookbooks/ey-hosts/templates/default/ey_hosts.erb
Example
--------------
```
#---EY-HOSTS-START
10.203.197.207        ey-app-master
10.230.182.98        ey-app-slave-0 …
```

Adjusts ey-hosts generation to only include hosts if their IP can be resolved at runtime

---

cookbooks/collectd/files/default/check_health_for

--------------
Corrects noisy FSCK healthcheck alerts (firing every 7 days with an OKAY status)
--------------
Eliminates redundant OKAY messages for filesystem healthchecks.
Estimated risk
--------------
Low
- minor changes that improve system visibility and improve performance
--------------
cookbooks/collectd/files/default/check_health_for
--------------
Manually adjusted the file on a live instance and verified the change corrected the issue seen.
--------------
on the app master instance, verify the first health-check OKAY status is received, wait 65 minutes (AWSM filters out redundant alerts)
touch -t 201704152240 …

bugfix for noisy filesystem check OKAY alerts

---

manifest/Gemfile
manifest/Gemfile.lock

--------------
Enhancements and bug fixes for eybackup/ey_cloud_server.
--------------
- Improves functionality and alerting for logical backups (eybackup).
- Corrects issue where mysql backups were recording database name in the backup
- Adds server identity to mysql backups to make them useful for replication-based restores
- Prevents and warns about overlapping backup runs; provides an override option off by default.
- cli improves backup errors when params specified incorrectly (leaving off db arg)
- listing backups with all now properly indexes multiple databases in environment
- OKAY messages only sent on first success after backup failure
- Error messages are printed to /var/log/engineyard/eybackup/#{dbname}.alert
- Backup Size …

Updates ey_cloud_server to 1.4.60 (DATA-479)

---

cookbooks/postgresql/recipes/postgis_build.rb

--------------
increase postgis install timeout for smaller instance types
--------------
Reduces the possibility of postgis install causing chef to timeout on instances with low CPU availability.
Estimated risk
--------------
Low
- Adds a timeout attribute that sets the timeout to 1200 seconds instead of the chef default of 600
--------------
cookbooks/postgresql/recipes/postgis_build.rb
--------------
The timeout condition is difficult to reproduce so there is no regression test with this PR
- booted a t2.micro solo instance
- deployed the updated codebase
- enabled the postgis extension by creating the file …

Increase postgis install timeout for smaller instance types (DATA-496)

---

cookbooks/collectd/files/default/check_health_for

-------------
We have a couple of customers with a custom nfs setup where the remote host directory is /data. For example,
```
domU-12-31-39-04-D9-8F.compute-1.internal:/data /shared [...]
```
As a result, our `check_primary-ebs` that supposedly checks the /data and /db volumes only, inadvertently matches this /shared volume.
Another issue is the nfs setup where the local mount point directory is the one matching /data or /db. For example:
```
appname@files.mydomain.com:/home/appname /data/client_data fuse.sshfs rw[...]
```
This change updates the `check_primary-ebs` to use a slightly stricter regex that prevents both these cases.
-------------
Excludes nfs remote host directory /data or /db from the primary EBS filesystem health check. …

CC-1181: Stricter /db and /data matching for check_primary-ebs.

---

cookbooks/elasticsearch/attributes/default.rb
cookbooks/elasticsearch/definitions/plugin.rb
cookbooks/elasticsearch/files/default/etc-security-limits.conf
cookbooks/elasticsearch/files/default/usr-local-bin-monit
cookbooks/elasticsearch/metadata.rb
cookbooks/elasticsearch/recipes/configure_cluster.rb
cookbooks/elasticsearch/recipes/configure_limits.rb
cookbooks/elasticsearch/recipes/default.rb
cookbooks/elasticsearch/recipes/install.rb
cookbooks/elasticsearch/templates/default/elasticsearch.in.sh.erb
cookbooks/elasticsearch/templates/default/elasticsearch.monitrc.erb
cookbooks/elasticsearch/templates/default/elasticsearch.yml.erb
custom-cookbooks/elasticsearch/cookbooks/custom-elasticsearch/README.md
custom-cookbooks/elasticsearch/cookbooks/custom-elasticsearch/attributes/default.rb
custom-cookbooks/elasticsearch/cookbooks/custom-elasticsearch/templates/default/jvm.options.erb

Adds Elasticsearch 5.x support
Adds Elasticsearch 5.x support
Low. 
Custom chef recipes
A. New Elasticsearch setup
Test on configuration A (solo) and B (cluster)
Under configuration B, add a utility instance named 'elasticsearch'
Follow the instructions in README to install Elasticsearch 5.5
Verify that Elasticsearch installs without any chef errors
Follow the instructions in README to configure the jvm options. 
Set the stack size (Xss) to 512k, upload and run chef, and restart Elasticsearch. Run `ps -ef | grep "[e]lastic"` to verify that the new Elasticsearch process is running with a 512k stack size.
B. Verify that current Elasticsearch setup still works
Test on configuration A (solo) with a utility instance named elasticsearch
Boot on the latest v5 stack
Follow the …

Add Elasticsearch 5.x support

---

cookbooks/postgresql/resources/pg_extension.rb

Fixes the chef error encountered when installing some PostgreSQL extensions
Fixes the chef error encountered when installing some PostgreSQL extensions
Low
PostgreSQL chef recipe
Test on configuration A
Boot latest stable-v5 stack
Follow the instructions in https://github.com/engineyard/ey-cookbooks-stable-v5/tree/next-release/cookbooks/postgresql#extensions to enable the following extensions:
- postgis
- uuid-ossp 
- auto_explain
Verify that chef fails when attempting to install uuid-ossp or one of the other extensions
Upgrade to the QA stack
Verify that chef runs cleanly and that the extensions have been installed
(To see the list of installed extensions, run `psql -U deploy todo -c "\dx"`)
Terminate the environment
Boot the environment again. Verify that there were …

CC-1194: Fix quoting of PostgreSQL extension names

---

cookbooks/elasticsearch/recipes/configure_limits.rb

The check was happening two places, first in https://github.com/engineyard/ey-cookbooks-stable-v5/blob/e390995050812566a4114cdb35040b1cb2fe6455/cookbooks/elasticsearch/recipes/default.rb#L13-L15
And then in https://github.com/engineyard/ey-cookbooks-stable-v5/blob/e390995050812566a4114cdb35040b1cb2fe6455/cookbooks/elasticsearch/recipes/configure_limits.rb#L6-L7
The second line prevents this from ever applying the changes. 
This partly fixes #231 .

Remove unnecessary that made the ElasticSearch recipe not apply limits

---

cookbooks/tinyproxy/libraries/cleanup_tinyproxy_monitrc.rb
cookbooks/tinyproxy/recipes/install.rb

also removes tinyproxy monitrc on non-tinyproxy instances

Tinyproxy: ensure tinyproxy directory is owned by nobody after a takeover

---

cookbooks/delayed_job4/templates/default/dj.erb

Properly recover when a DelayedJob worker was terminated and is lingering as a zombie process.
There is a bug here: https://github.com/engineyard/ey-cookbooks-stable-v5/blob/7310e1b6d22d94a352aa6c011f1200284c394d4a/cookbooks/delayed_job4/templates/default/dj.erb#L51-L62
The test 
```
if [ -n $LAST_LOCK_PID -a -z " ps axo pid|grep $LAST_LOCK_PID" -a -f $LOCK_FILE ];then 
``` 
tests if $LAST_LOCK_PID is defined and there’s no running process with that pid, but there is a lock file. It goes to the "Monit already messing with..." block if there is a running process, even if it's a zombie process. 
This PR adds an additional test to check if the PID matches a running process but the process is a zombie.
Updates the delayed_job4 recipe to properly handle zombie workers
Low
DelayedJob custom …

CC-1206: Add a check for zombie DJ workers

---

cookbooks/cron/recipes/default.rb
custom-cookbooks/cron/cookbooks/custom-cron/README.md

Cron recipe is extended to allow the use of keywords "all", "util", "app" and "db" apart from instance name
N/A
Low
README
Tested on an env with util/app_master/app server. Different cronjobs were set up based on keywords
No QA needed

adds capability to select util,app,db or all instances. fixes #239

---

cookbooks/passenger5/attributes/passenger5.rb

Updates Passenger to version 5.1.8
Updates Passenger to version 5.1.8. This version fixes a number of bugs, and is backwards-compatible with Passenger 5.0.29. If you need to stay on Passenger 5.0.29, you can override the Passenger version by following the instructions here: https://github.com/engineyard/ey-cookbooks-stable-v5/wiki/Customizing-Your-Environment-Using-Overlay-Chef-Recipes
Medium
Passenger5 recipe
Boot a solo and a cluster environment running Passenger 5. Verify that there are no chef errors, and `passenger -v` returns 5.1.8 on the solo/app_master/app instances.

Upgrade to Passenger 5.1.8

---

cookbooks/emerge/files/default/portage-mirror
cookbooks/emerge/recipes/default.rb
cookbooks/emerge/recipes/ensure_mirror.rb

Create the portage mirror file
None.
Medium. eix-sync can break if there's a typo on the created mirror file
Portage
This can be tested along with other test cases.
1) New environment scenario
- Boot a cluster environment under the QA stack. 
- On all instances, verify that the `/etc/portage/mirrors` file exists and has the content: `local http://cloud.distfiles.eygl.engineyard.com/2016.06`
- Verify that all the instances ran chef without errors
- Add a new app instance and verify that the new instance did not encounter a chef error
- Add a new utility instance and verify that the new instance did not encounter a chef error
2) Upgrade scenario
- Boot a cluster environment under the latest V5 stack.
- On all instances, verify that `/etc/portage/mirrors` does not exist, …

CC-1210: Create portage mirror file

---

cookbooks/delayed_job4/templates/default/dj.erb

This fixes a typo in https://github.com/engineyard/ey-cookbooks-stable-v5/pull/251. Test scenarios should remain the same as in PR #251

DelayedJob: Fix zombie worker test

---

cookbooks/postgresql/recipes/server_configure.rb
cookbooks/postgresql/templates/default/postgresql.conf.erb

--------------
Adds explicit default timezone setting to Postgres in support of the Timezones DNA feature.
--------------
Adds support for timezone controls to PostgreSQL
Estimated risk
--------------
Low
- Nothing is changed if the timezone is unrecognized or not present.
--------------
cookbooks/postgresql9/recipes/server_configure.rb
cookbooks/postgresql9/templates/default/postgresql.conf.erb
--------------
Under the 12.11 stack
- Provisioned a solo using the updated stack
- Verified cookbooks completed successfully
- Verified the current timezone with `psql -c 'show timezone'` showed a value of `GMT`
- Added an attribute `"timezone": …

Add timezone attribute to postgresql.conf

---

cookbooks/timezones/recipes/default.rb

--------------
Adjusts timezone feature to restart nginx when timezone is updated
--------------
Feature is not useable yet, no release note required. 
Estimated risk
--------------
Low
- Corrects what would have been a bug in an already low risk feature.
--------------
cookbooks/timezones/recipes/default.rb
--------------
- Provisioned a solo using the updated stack
- Verified cookbooks completed successfully
- Verified the current timezone with `ls -la /etc/localtime` showed a symlink to `/usr/share/zoneinfo/UTC`
- Added an attribute `"timezone": "America/Anchorage"` in `/etc/chef/dna.json` under `"engineyard":"environment"`
- Check the …

Correct dna attribute so nginx is restarted on tzone change

---

cookbooks/elasticsearch/attributes/default.rb
cookbooks/elasticsearch/recipes/default.rb
custom-cookbooks/elasticsearch/cookbooks/custom-elasticsearch/attributes/default.rb

I think we should use `is_elasticsearch_instance` as a primary way of configuring where we install elasticsearch servers. 
This recipe does not support running elasticsearch on `solo` or `app_master` instances because of the guards setup in `install.rb`:
```ruby
elasticsearch_hosts = []
node['dna']['utility_instances'].each do |instance|
if instance['name'].include?("elasticsearch_")
elasticsearch_hosts << "#{instance['hostname']}:9200"
end
end
```

Deprecate configure_cluster in favor of new variable is_elasticsearch_instance

---

cookbooks/postgresql/attributes/extension_details.rb
cookbooks/postgresql/attributes/version.rb
cookbooks/postgresql/recipes/server_configure.rb
cookbooks/postgresql/recipes/server_install.rb

--------------
Updates Postgresql-server 9.5 to 9.5.7
Adds new major version for 9.6 of 9.6.3.
Adds Postgis 2.3.3 to support Postgres 9.6
--------------
Adds support for Postgres versions 9.5.7 and 9.6.3
Estimated risk
--------------
Low
- Customers need to take additional steps to apply this update or must have opted in to automatic updates.
- Recommended procedure for databases is to always test new releases in a non-Production environment before upgrading Production.
--------------
cookbooks/postgresql/attributes/version.rb
cookbooks/postgresql/recipes/server_configure.rb
cookbooks/postgresql/recipes/server_install.rb
cookbooks/postgresql/attributes/extension_details.rb …

Bump minor Postgres 9.5 version to 9.5.7, add Postgres 9.6 with 9.6.3

---

custom-cookbooks/memcached/cookbooks/custom-memcached/attributes/default.rb

- Set the default version to the latest valid version available on the portage tree
- Disable the download_url setting - this is only used if install_from_source is set to true

[memcached] Set the default version

---

docs/how_it_works.md

- Removed the sentence that says it's ok to target master for doc-only changes. We always want PRs to be against next-release, even doc-only changes. This makes it easier to avoid merge conflicts.
- Request that contributors merge against next-release before submitting the PR. This way, in case they started working on the PR a few releases ago, they update against recent releases and we avoid merge conflicts.

Update contribution instructions

---

cookbooks/cdn_distribution/attributes/default.rb
cookbooks/cdn_distribution/recipes/default.rb
cookbooks/env_vars/attributes/default.rb
cookbooks/env_vars/recipes/cloud.rb
cookbooks/env_vars/recipes/default.rb
custom-cookbooks/env_vars/cookbooks/custom-env_vars/README.md
custom-cookbooks/env_vars/cookbooks/custom-env_vars/attributes/default.rb

Customers expect our chef runs to be "safe" and expect that in general there is no risk of causing a downtime when running chef. Doing the application restart in chef will do a near-simultaneous restart across all application instances, which will almost certainly cause downtime.
This PR removes the application restarts from the chef recipes. For recipes that need an application restart, e.g. env_vars and cdn_distribution, we should (1) clarify that a restart is needed for the change to take effect, and (2) provide instructions on how to do a staggered restart in the README.

Remove application restarts

---

cookbooks/delayed_job4/templates/default/dj.monitrc.erb

monit's default timeout of 60s for the DJ stop command is the same as the timeout used when terminating a dj worker. As a result, if the dj worker is unresponsive, monit's stop command times out and the worker does not get terminated. This patch updates the default monit timeout to make it higher than the worker timeout.
Sets the monit stop timeout to a higher value to ensure that dj worker processes are terminated when they hit the monit memory limit.
Low
DelayedJob custom chef recipe
Test on configuration A_dj
Configuration A
rails_activejob_example (delayed_job branch) App 
Unicorn
Ruby 2.3
RubyGems 2.6.5
Postgres 9.5
US East Virginia
Solo
Boot the test environment under the current stable-v5 stack
Enable the delayed_job recipe
Modify the recipe to install …

DelayedJob4: Resolves #284

---

cookbooks/postgresql/recipes/server_configure.rb

--------------
Fixup default timezone setting for Postgres replicas.
--------------
Hotfix: corrects timezone controls for PostgreSQL replicas
Estimated risk
--------------
Low
- Nothing is changed if the timezone is unrecognized or not present.
--------------
cookbooks/postgresql9/recipes/server_configure.rb
--------------
- Provisioned a cluster using the updated stack
- Verified cookbooks completed successfully
- Created a replica database, and against the replica:
- Verified the current timezone with `psql -c 'show timezone'` showed a value of `GMT`
- Added an attribute `"timezone": "America/Anchorage"` in `/etc/chef/dna.json` …

add configuration settings for timezone to Postgres replicas

---

cookbooks/postgresql/recipes/client_config.rb

--------------
Fixup removes pg_host entry from .bash_login
--------------
Hotfix: removes environment variable that prevents Postgres replica promotions on stable-v5-3.0.33+
Estimated risk
--------------
Low
- Nothing depends on this environment variable at this time.
--------------
cookbooks/postgresql/recipes/client_config.rb
--------------
- Provisioned a cluster with PostgreSQL using the current stack
- add a replica database
- promote the replica database when healthy
- the promotion will fail
- try to access psql client on the replica, this will fail and suggest postgres may not be running on a given EC2 hostname
- terminate …

fixup to remove PGHOST entry from .bash_login; this can block replica promotions

---

cookbooks/security_updates/recipes/default.rb

Verified the dev-libs/libxml2 has been upgraded to 2.9.4 from 2.9.3 for security purposes
Verified that fix has been tested and works accordingly. 
https://tickets.engineyard.com/issue/CC-1203

CC-1203 Updates dev-libs/libxml2 for security

---

cookbooks/openssl/attributes/openssl.rb

https://tickets.engineyard.com/issue/CC-1146

default openssl version update for the openssl cookbook. Ticket: CC-1146

---

cookbooks/security_updates/recipes/default.rb

https://tickets.engineyard.com/issue/CC-924

security update of package net-libs/gnutls to 3.3.28. Ticket: CC-924

---

cookbooks/elixir/attributes/elixir.rb

-------------
Updates erlang in the elixir cookbook from 18.3 to 19 due to an erlang regression with Openssl
-------------
Updates Elixir Erlang from 18 to 19
Estimated risk
-------------
Low - unreleased stack
-------------
elixir
-------------
The attribute change was tested via an overlay with elixir enabled
I updated the attributes file with the desired Erlang version
-------------
Boot up a solo environment using the QA stack.
Check that iex shows OTP 18
Update cookbooks and verify iex shows OTP 19

Update Erlang from 18.3 to 19 due to regression

---

cookbooks/papertrail/attributes/default.rb
cookbooks/papertrail/recipes/default.rb
custom-cookbooks/papertrail/cookbooks/custom-papertrail/README.md
custom-cookbooks/papertrail/cookbooks/custom-papertrail/attributes/default.rb

-------------
Add new attribute for Papertrail cookbook to specify instances where it will run. Update custom-papertrail README to explain this customization.
Fixes #217.
-------------
Papertrail cookbook can now be configured to only setup in certain instances.
Estimated risk
-------------
Low - only affects environments with papertrail enabled.
-------------
Papertrail (syslog services)
-------------
Setup a cluster (app master, db master, utility named "papertrail"), and enabled added custom-papertrail recipe. By default, Papertrail is setup in all instances.
Then, I manually updated cookbooks/papertrail for the new changes, and updated cookbooks/custom-papertrail to specify it to run …

CC-1188: Allow specifying instances to run for Papertrail.

---

cookbooks/newrelic_infra/README.md
cookbooks/newrelic_infra/attributes/default.rb
cookbooks/newrelic_infra/files/default/newrelic_infra.monitrc
cookbooks/newrelic_infra/metadata.rb
cookbooks/newrelic_infra/recipes/default.rb
cookbooks/newrelic_infra/templates/default/newrelic-infra.erb
cookbooks/newrelic_infra/templates/default/newrelic-infra.yml.erb
custom-cookbooks/newrelic_infra/README.md
custom-cookbooks/newrelic_infra/cookbooks/custom-newrelic_infra/README.md
custom-cookbooks/newrelic_infra/cookbooks/custom-newrelic_infra/attributes/default.rb
custom-cookbooks/newrelic_infra/cookbooks/custom-newrelic_infra/metadata.rb
custom-cookbooks/newrelic_infra/cookbooks/custom-newrelic_infra/recipes/default.rb
custom-cookbooks/newrelic_infra/cookbooks/ey-custom/metadata.rb
custom-cookbooks/newrelic_infra/cookbooks/ey-custom/recipes/after-main.rb

-------------
Initial version of the New Relic Infrastructure recipe. The recipe installs the New Relic Infrastructure agent in all the instances in the environment by downloading the .deb, extracting its contents, rewriting the init script, installing monit control file and reloading monit.
-------------
Adds a custom chef recipe to setup the New Relic Infrastructure agent.
Estimated risk
-------------
Low - only affects customers who enable the custom-newrelic_infra recipe.
-------------
newrelic-infra
-------------
Tested on a simple cluster: one app master, one db master. Verified the following:
* .deb file is downloaded and extracted
* Ran `/usr/bin/newrelic-infra` -version to report …

CC-1217: Initial version of the New Relic Infra recipe

---

cookbooks/passenger5/files/default/passenger_monitor

-------------
The newer Passenger 5.1.8 installs passenger-status on `/usr/local/bin/passenger-status`. The older version has it on `/usr/sbin/passenger-status`.
For customers who have upgraded to the v5 stack with Passenger 5.1.8, the orphan killer portion of passenger_monitor cron job is broken for hardcoding `/usr/sbin/passenger-status`.
The fix simply changes `/usr/sbin/passenger-status` to `passenger-status`.
-------------
Fixes passenger-status path in the passenger_monitor cron job.
Estimated risk
-------------
Low - very small change that only tries to fix the wrong passenger-status path, worst case scenario is it's still not fixed
-------------
Passenger (passenger_monitor cron job)
Description of testing …

CC-1219: Fix passenger-status path on v5 passenger_monitor cron job.

---

cookbooks/nginx/files/default/nginx

Introduce a fix for init.d losing track of running processes
N/A
Medium 
README
1. Remove nginx PID file: `rm -rf /var/run/nginx.pid`
2. Reload nginx via `/etc/init.d/nginx reload`

Introduce a fix for init.d losing track of running processes

---

cookbooks/haproxy/templates/default/haproxy.cfg.erb
cookbooks/lb/templates/default/haproxy.cfg.erb
cookbooks/nginx/templates/default/common.fcgi.conf.erb

Adding header HTTP_X_FORWARDED_PORT to haproxy configuration to be able to use real request port for FastCGI applications
None.
Low
HAPROXY, Nginx
1. Create simple PHP application. Simple How-To app (git://github.com/engineyard/howto.git) can be used for this testing.
4. Run command `curl 127.0.0.1/phpinfo.php | grep SERVER_PORT`
5. Ensure PHP SERVER_PORT variable is set to 8081.
6. Replace nginx and haproxy cookbooks with relevant cookbooks provided in current pull request.
7. Run Chef `PATH=/usr/local/ey_resin/bin:$PATH /home/ey/bin/chef-solo -j /etc/chef/dna.json -c /etc/chef/solo.rb`
8. Run …

[CC-666] Add header HTTP_X_FORWARDED_PORT to haproxy

---

cookbooks/ey-base/recipes/chef_patches.rb

Currently Chef determines this by parsing 'emerge', which is time consuming and error prone. This PR/change results in a large speed increase for Gentoo-based systems and Engine Yard's cookbooks.
-------------
Rewrites candidate_version determination in Chef's Chef::Provider::Package::Portage class for increased speed and reduced complexity/error-chance.
-------------
Speed improvements to the execution of Chef cookbooks package resource.
Estimated risk
-------------
Touches sensitive/low-level chef interfaces to the OS packaging manager for Gentoo systems. So potentially high risk. However, the changes have been tested thoroughly and best efforts have been made to be a fully-compatible drop-in replacement. …

[YT-CC-1236] Rewrite candidate_version determination for increased speed and reduced complexity/error-chance

---

cookbooks/ntp/templates/default/ey-ntp-check.erb

-------------
Check separately to see if ntpd is running and restart it if not. This resolves an issue where the test for stale peers failed silently without ntpd being restarted if the ntpd process itself was not running.
-------------
Resolves an issue with detecting a crashed ntpd process.
Estimated risk
-------------
Low - we monitor separately for ntpd failures, this change is intended to fix one failure mode that isn't currently handled automatically.
-------------
`/engineyard/bin/ey-ntp-check` - a script which is called from cron.
-------------
Booted an instance, copied in the modified script and then tested that the script successfully detects and corrects both a stopped and a …

[CC-1150] Handle crashed ntpd processes gracefully.

---

cookbooks/elixir/templates/default/nginx_app.conf.erb
cookbooks/nginx/files/default/mime.types
cookbooks/nginx/templates/default/fpm-server.conf.erb
cookbooks/nginx/templates/default/fpm-ssl.conf.erb
cookbooks/nginx/templates/default/server.conf.erb
cookbooks/nginx/templates/default/ssl.conf.erb
cookbooks/passenger5/templates/default/nginx_app.conf.erb
cookbooks/puma/templates/default/nginx_app.conf.erb

Adding CORS header to font files, to be able to use this file in cross domain applications
None.
Low
Nginx
1. Create simple Ruby application. Simple TO-DO app (https://github.com/engineyard/todo.git) can be used for this testing.
* Application Server Stack - Passenger 5
* Runtime - Ruby 2.3
4. Replace nginx cookbook with cookbook provided in current pool request.
5. Run Chef `PATH=/usr/local/ey_resin/bin:$PATH /home/ey/bin/chef-solo -j /etc/chef/dna.json -c /etc/chef/solo.rb`
4. Create test.svg file in folder /data/<YOUR_APPLICATION_NAME>/current/public. Content for this file can be taken from: …

[CC-938] Update on Nginx config for handling fonts and CDNs

---

custom-cookbooks/fail2ban/cookbooks/custom-fail2ban/README.md

-------------
In the README of custom-fail2ban, installation suggests that you edit cookbooks/ey-custom/fail2ban/after-main.rb. This is a typo and should be cookbooks/ey-custom/recipes/after-main.rb.
-------------
Not Applicable. Customers will not get any changes on a stack upgrade because this is under custom-cookbooks.
Estimated risk
-------------
Low - Only updates README of a custom cookbook.
-------------
Custom fail2ban.
-------------
No testing needed. Just a README typo fix.
-------------
No testing needed. Just a README typo fix.

CC-1231: Fix typo in custom-fail2ban README.

---

cookbooks/newrelic_infra/attributes/default.rb
cookbooks/newrelic_infra/metadata.rb
cookbooks/newrelic_infra/recipes/default.rb
cookbooks/newrelic_infra/templates/default/newrelic-infra.yml.erb
custom-cookbooks/newrelic_infra/cookbooks/custom-newrelic_infra/README.md
custom-cookbooks/newrelic_infra/cookbooks/custom-newrelic_infra/attributes/default.rb

-------------
The update adds two new attributes:
* `default['newrelic_infra']['use_newrelic_addon']` - set to `true` to indicate that you want to use the license key from the New Relic add-on. When using this, there's no need to specify the license key with `default['newrelic_infra']['license_key']`.
* `default['newrelic_infra']['display_name']` - sets the `display_name` New Relic Infra configuration setting (see https://docs.newrelic.com/docs/infrastructure/new-relic-infrastructure/configuration/configure-infrastructure-agent).
The README has been updated to describe these new attributes, and a Credits section was also added.
-------------
New Relic Infrastructure custom chef recipe adds new attributes to support using license key from …

[YT-CC-1217] credits section, support license key from NR add-on and display name

---

cookbooks/sidekiq/attributes/default.rb
cookbooks/sidekiq/files/default/sidekiq_orphan_monitor
cookbooks/sidekiq/recipes/setup.rb

Github note: This closes issue #279 
Adds orphan monitoring to the sidekiq recipe
Adds orphan monitoring to the sidekiq recipe
Low. Only the sidekiq recipe is changed. The new feature is disabled by default.
sidekiq custom chef recipe
Tested the unit tests on a solo environment with redis and sidekiq utility instances
Enable both the redis and the sidekiq recipes. 
Modify `custom-sidekiq/attributes/default.rb` and set `sidekiq['orphan_monitor_enabled']` to true
Upload the chef recipe before booting the environment.
Boot a new cluster environment for the rails_activejob_example application
- Unicorn
- Ruby 2.3
- Rubygems 2.6.3
- Postgres 9.4
- any region
- QA stack
The cluster should have the following instances:
- 1 app_master
- 1 redis
- 1 sidekiq
- 1 db_master
On the sidekiq instance: …

[YT-CC-1204] Adds orphan monitoring to the sidekiq recipe

---

cookbooks/nginx/templates/default/server.conf.erb
cookbooks/nginx/templates/default/ssl.conf.erb
cookbooks/passenger5/templates/default/nginx_app.conf.erb

Adding nginx configuration changes to hide the X-Powered-By header
None.
Low
Nginx
1. Create simple Ruby application. Simple TO-DO app (https://github.com/engineyard/todo.git) can be used for this testing.
* Application Server Stack - Passenger 5
4. Replace nginx and passenger5 cookbook with cookbook provided in current pool request.
5. Run command `curl -I 127.0.0.1`
6. Ensure X-Powered-By header is provided in reply.
5. Run chef `PATH=/usr/local/ey_resin/bin:$PATH /home/ey/bin/chef-solo -j /etc/chef/dna.json -c /etc/chef/solo.rb`
6. Run command `curl -I 127.0.0.1`
7. Ensure X-Powered-By header …

[CC-1179] Hide passenger version on X-Powered-By header

---

cookbooks/db-ssl/templates/default/remote_key_copy.sh.erb

The `remote_key_copy.sh` script that is generated, when there are
stopped instances in the environment, causes chef runs to take
upwards of nine extra minutes per stopped instance. This is because
the `push_keys` function in this script, which uses `rsync` to copy
a few key files to each instance in the environment, and the
connection timeout is around 3 minutes by default.
Additionally, the `push_keys` function is used (contextually) to
copy those same files to the db replicas in the environment, but
this is not actually happening due to the use of global variables.
Changes:
* Defined an `is_up` function that takes an instance as an argument.
It then attempts to ssh to the instance and run `date`. If this
should fail, it returns false. Otherwise, it is true. Either way
it has a …

db-ssl timeouts and corrections

---

cookbooks/ey-lib/libraries/ey-environment.rb
cookbooks/ruby/recipes/ruby.rb

-------------
Add support for Ruby 2.5.
-------------
Support for Ruby 2.5.
Estimated risk
-------------
High. Changes are made to the ruby recipes which are a central part of the stack.
-------------
Ruby chef recipes and `default_ruby_version` in cookbooks/ey-lib/libraries/ey-environment.rb.
-------------
Created a development stack (based on stable-v5 3.0) with this branch and booted a solo environment (todo app) with "Ruby 2.5" selected.
Verified that the app can deployed successfully.
Verified that the expected ruby package (`=dev-lang/ruby-2.5.1`) was installed and selected by default.
-------------
See above.

[CC-1248] Support for Ruby 2.5

---

cookbooks/php/attributes/php.rb

Add support for PHP 7.2.
Support for PHP 7.2.
High. Changes are made to the php recipes which are a central part of the stack.
PHP chef recipes.
1. Created a development stack (based on stable-v5 3.0) with this branch and booted a solo environment (howto app) with "PHP 7.2" selected.
Verified that the app can be deployed successfully.
Verified that the expected php package (=dev-lang/php-7.2.8) was installed and selected by default.
2. Created a stable-v5 solo environment (howto app) with "PHP 7.1" (sic!) selected.
Verified that the app can be deployed successfully.
Then, edited the environment and upgraded to the development stack with this branch.
Applied the upgrade and checked if the app still works.
Edited the environment again and selected "PHP 7.2".
Applied and tested for …

[CC-1250] Support for PHP 7.2

---

cookbooks/node/attributes/node.rb
cookbooks/node/recipes/common.rb

-------------
This enables support for node.js series 8.x, 9.x, and 10.x in stable-v5. It will use the EYGL net-libs/nodejs-bin packages.
-------------
Support for node.js 8.x, 9.x, and 10.x.
Estimated risk
-------------
Medium. We only add new versions of node.js. Nevertheless, this is a core recipe which is used for node.js apps and for ruby apps (asset compilation) as well.
-------------
node recipes
-------------
- Create a ruby app with selected node 8 on the QA stack. Boot the environment, deploy, check if it works.
- Create a ruby app with default node on stable-v5. Boot the environment, deploy, check if it works.
- Upgrade to the QA stack with this PR. Apply, deploy, check if it …

[CC-1252] Enable support for node.js series 8.x, 9.x, and 10.x

---

cookbooks/collectd/attributes/defaults.rb
cookbooks/collectd/recipes/httpd.rb
cookbooks/collectd/templates/default/collectd_nginx_version.conf.erb

This patch allows to reduce Chef running time on working environment by ~10 seconds. 
None
Low
Collectd Nginx service
1. Create a simple Ruby application.  (https://github.com/engineyard/todo.git) can be used for this testing.
2. Boot the environment with QA stack created from the PR282_improvement branch. Environment should be run with following parameters:
* Application Server Stack - Passenger5.
4. Replace collectd cookbook with cookbook provided from this pull request branch. 
5. Run Chef `PATH=/usr/local/ey_resin/bin:$PATH /home/ey/bin/chef-solo -j /etc/chef/dna.json -c /etc/chef/solo.rb`. Fix the Chef running time.
6. Run Chef again. Ensure Chef took ~10 seconds less to run.
7. Run command `monit summary`. Ensure …

[YT-CC-1241] Collectd cookbook calls Nginx upgrade on every Chef run

---

cookbooks/prompt/recipes/default.rb

Fixing "prompt" recipe in order to run successfully on instance boot
N/A
Low
prompt recipe
Boot the environment with QA stack
Ensure chef completes successfully
Switch to "deploy" user via `su - deploy`
Confirm that prompt is providing information

fix prompt recipe in order to run successfully on instance boot

---

cookbooks/postgresql/attributes/extension_details.rb
cookbooks/postgresql/attributes/version.rb
cookbooks/postgresql/libraries/helpers.rb
cookbooks/postgresql/recipes/server_configure.rb
cookbooks/postgresql/recipes/server_install.rb
cookbooks/postgresql/resources/pg_extension.rb
cookbooks/postgresql/templates/default/postgresql.conf.erb
cookbooks/postgresql/templates/default/recovery.conf.erb
manifest/Gemfile
manifest/Gemfile.lock

-------------
This adds support for PostgreSQL 10.x.
-------------
Add support for PostgreSQL 10.
Estimated risk
-------------
High. PostgreSQL is a central component of the stack and very complex.
-------------
The postgresql recipes, ey_snaplock (primer resins are updated)
-------------
Booted production environments on a testing stack with the cookbooks changes (and updated resins) with PostgreSQL 9.5 and PostgreSQL 10.
Performed a master takeover on each environment.
After completed takeover, added a new db slave to the environment.
During those steps, tested if the application can be deployed and works.
@johndalton also did testing with this.
-------------
See above. …

[CC 1249] Support for PostgreSQL 10

---

cookbooks/ey-init/recipes/integrate.rb

Fixing SSL keys distribution on instance addition
Fixing SSL keys distribution on instance addition
Low
ey-init/integrate recipe
- Boot a multi-instance env using the QA stack (without util instance)
- Add util instance
- Verify that the following is no longer an issue:```The .mysql folder doesn't exist on the new instance and it throws an error during integration```

adding db-ssl cookbook on quick chef run

---

cookbooks/haproxy/templates/default/haproxy.cfg.erb

Fixing healthcheck path monitoring on HAproxy
N/A
Medium
Template file haproxy.cfg.erb
- Configure "Haproxy Health Check Path" on application settings. Use an existing path
- Boot a multi-instance environment under the application configured above using the QA stack 
- Verify that /etc/haproxy.cfg contains under "listen cluster" and/or "listen clusterssl":
```
option httpchk HEAD <HEALTHCHECK_PATH_CONFIGURED> HTTP/1.1\r\nHost:\ <HOST_CONFIGURED>
http-check expect rstatus ((2|3)[0-9][0-9]|503)
```
- Edit /etc/haproxy.cfg, add the following under "global"
```
log /dev/log    local0
log /dev/log    local1 notice
```
RESTART HAproxy: `/etc/init.d/haproxy restart`
- Tail `/var/log/syslog` for HAproxy logs, verify servers's status. All should be up
- Modify "Haproxy Health …

fixing application healthcheck on haproxy

---

cookbooks/prompt/recipes/default.rb

Correcting default user on prompt cookbook, this will save time and the need to modify the prompt chef recipe.
N/A
Low
/cookbooks/prompt/recipes/default.rb
/cookbooks/prompt/*
Run the chef recipe on the v5 stack.
1st. Download the changes.
2nd. Perform chef overlay.
3rd. Create a test environment with a user not deploy
4th. Upload the custom recipe to the environment.
5th. SSH into the test instance with the custom user created.

Get default user fix.

---

cookbooks/haproxy/templates/default/haproxy.cfg.erb
cookbooks/lb/templates/default/haproxy.cfg.erb

Changing httpclose parameter to the http-server-close for HAPROXY. This allows you to use keepalive connection on client side.
More about HAPROXy connection serving modes: https://www.haproxy.com/documentation/aloha/7-0/traffic-management/lb-layer7/http-modes
None.
Low
HAPROXY
1. Create simple Ruby application. Simple TO-DO app (https://github.com/engineyard/todo.git) can be used for this testing.
* Application Server Stack - Passenger 5
* Runtime - Ruby 2.3
4. Replace haproxy cookbook with cookbook provided in current pool request.
5. Run chef `PATH=/usr/local/ey_resin/bin:$PATH …

[CC-629] Change haproxy option value to http-server-close

---

cookbooks/unicorn/templates/default/unicorn.rb.erb

-------------
The comment above says `QUIT`, but the code does `TERM`.
According to documentation: https://bogomips.org/unicorn/SIGNALS.html
TERM - quick shutdown, kills all workers immediately
QUIT - graceful shutdown, give workers some time to finish their current request before finishing.
Therefore, usual safe scenario of restarting unicorn during deployment involves using `QUIT`.
-------------
Deployment of application using unicorn use graceful restarting, which prevents requests to be killed without giving them chance to finish.
Estimated risk
-------------
low
-------------
unicorn
-------------
Deployed the same fix to our application.
-------------

Use graceful restart in unicorn

---

custom-cookbooks/sidekiq/cookbooks/custom-sidekiq/README.md

Adds a configuration example on how to have the recipe set sidekiq.yml with queues & priorities per worker

Examples of queues per worker in Sidekiq

---

manifest/Gemfile
manifest/Gemfile.lock

-------------
Update the version of the ey_enzyme gem to 2.0.6. This fixes a bug where ohai does not properly populate the ec2 metadata object.
-------------
Fix populating the `node['ec2']` object.
Estimated risk
-------------
High. The ey_enzyme gem is responsible for running chef when performing an "Apply".
-------------
ey_enzyme gem, primer
-------------
Created a testing stack.
Uploaded custom chef recipes for each environment which install and configure sidekiq (thereby accessing the node['ec2'] object).
Booted a new environment with the testing stack and deployed the `dummy-sidekiq` branch of the todo app. Tested if cookbook run is successful and sidekiq workers are started.
Booted …

[CC-1325] Update ey_enzyme gem

---

cookbooks/papertrail/recipes/default.rb

Update default.rb
Updated check sum of papertrail and removes old sysklogd cronjobs
N/A
Estimated risk
Low
cookbooks/papertrail/recipes/default.rb
Check QA instructions
Create a test environment
Add paper trail via chef.
Upload and Apply chef.
ssh into environment 
check paper trail
check /etc/crontab.daily/syslog and /etc/crontab.weekly/syslog ensue "/etc/init.d/sysklogd --quiet reload" is removed

Updated Checksum for papertrail

---

cookbooks/delayed_job4/templates/default/dj.erb

Reverting pull request https://github.com/engineyard/ey-cookbooks-stable-v5/pull/343 as introduced a buggy behavior on customers not running named queues.
Reverting pull request https://github.com/engineyard/ey-cookbooks-stable-v5/pull/343 as introduced a buggy behavior on customers not running named queues.
Low
templates/default/dj.erb
QA performed on customers' environments

reverting PR #343

---

cookbooks/delayed_job4/attributes/default.rb

Update DelayedJob recipe to calculate the number of workers on Gen5 EC2 instances
Update DelayedJob recipe to calculate the number of workers on Gen5 EC2 instances
Low
attributes/default.rb
- Enable DJ recipe
- Boot various gen5 instances
- Confirm that the number of workers is dynamically calculated based on instance type

Calculate DJ workers on Gen5 instances 

---

cookbooks/cron/recipes/default.rb
custom-cookbooks/cron/cookbooks/custom-cron/README.md

Adding the "app_master" option on cron recipe allowing installation of cronjobs on app_master instance (exclusively)
Adding the "app_master" option on cron recipe allowing installation of cronjobs on app_master instance (exclusively)
Low
custom-cron/README.md
cron/recipes/default.rb
- Boot environment with app_master + app instance
- Configure `custom-cron` recipe to install cronjob on app_master only
- Confirm cronjob installation on app_master (only)

Τune cron recipe to allow cronjob installation on app master only

---

cookbooks/mysql/recipes/extras.rb
cookbooks/postgresql/recipes/setup_app_users_dbs.rb
cookbooks/reboot/templates/default/9999_reboot.start.erb

Updates the `9999_reboot.start` script to ensure v5 instances do a full Chef run, in response to missing `/var/run/engineyard` prevents Unicorn starting up if an instance is restarted multiple times consecutively.
Also updates MySQL `extras` recipe to use password as former no password method fails on post restart run.
Also updates PostgreSQL `setup_app_users_dbs` recipe to use `localhost` for the DB hostname on instances running DBs, as hostname from DNA does not yet resolve to updated private IP that soon after instance restart and thus access is blocked by AWS SG. On other instances it still resolves to host from DNA in order that it works with RDS still.
Some QA already done, tested on solo (both EIP and public hostname) and multi instance environments, with Unicorn and Passenger and …

Updating reboot script to ensure full Chef run on v5

---

cookbooks/haproxy/recipes/configure.rb
cookbooks/haproxy/templates/default/haproxy.cfg.erb

Changes the handling of the certificates variable. Should make no difference for general usage, but prevents the need to overlay the haproxy recipe for the custom-haproxy-ssls custom recipe.

Add certificates variable and lazy load it

---

cookbooks/ey-dynamic/recipes/rubygems.rb
cookbooks/passenger5/recipes/install.rb
cookbooks/ruby/files/default/gemrc
cookbooks/ruby/recipes/install.rb
cookbooks/ruby/recipes/rubygems.rb

(This PR also includes #394. I can rebase after #394 is merged if necessary)
Remove --no-ri --no-rdoc 
Add /root/.gemrc with --no-ri --no-rdoc --no-document
Note: .gemrc having `--no-ri --no-rdoc` on rubgyems 3 and `--no-document` on rubygems 2 is not a problem. `gem` commands won't fail.  `gem install` will only fail with `--no-ri --no-rdoc` on rubygems 3 if you use the flags on the command line *NOT* on .gemrc

Add --no-document on /root/.gemrc

---

cookbooks/memcached/recipes/install.rb
cookbooks/memcached/templates/default/memcached.monitrc

Update PID file that monit tracks based on memcached version
Fixes `monit` configuration file for `memcached` version > 1.4.39
Low
install.rm
Boot env with memcached version <  1.4.39
Confirm that memcached PID file is _/var/run/memcached.pid_ and `monit` keeps track of process
Boot env with memcached version >=  1.4.39
Confirm that memcached PID file is _/var/run/memcached-11211.pid_ and `monit` keeps track of process

Update PID file based on memcached version

---

cookbooks/monit/attributes/monit.rb
cookbooks/security_updates/recipes/default.rb

-------------
Update the hard-coded versions of `media-libs/tiff`, `net-misc/curl`, and `app-admin/monit` to the latest stable versions with the most recent security fixes.
-------------
Update OS packages to the latest versions.
Estimated risk
-------------
Medium. All updates are minor, only introducing fixes for security vulnerabilities. However, monit is a major component.
-------------
`security_updates` cookbook and `monit` cookbook
-------------
Booted a solo env with a testing stack that includes this PR (Ruby todo app).
Made sure the environment boots successfully, deploys the app, and the app works.
Logged into the instance and verified that the updated package versions got …

[CC-1351] Prevent package downgrades

---

cookbooks/ey-lib/libraries/ey-environment.rb
cookbooks/ruby/attributes/versions.rb
cookbooks/ruby/recipes/rubygems.rb

-------------
Add support for Ruby 2.6.
-------------
Add support for Ruby 2.6.
Estimated risk
-------------
Medium. Existing (non-Ruby 2.6) environments should not be affected by the change.
-------------
Ruby recipes
ey-environment library
-------------
0. Created a testing stack with this PR and https://github.com/engineyard/ey-cookbooks-stable-v5/pull/402.
1. Booted a solo environment with Ruby 2.5 [sic].
2. On the instance, synced the Ruby 2.6 ebuilds.
3. Updated the environment to Ruby 2.6 and lock serverside version to 2.6.19.
4. Checked if it applies correctly and deploys successfully.
5. Downgraded to Ruby 2.5 and checked if it works.
-------------
This PR must be …

[FB-462] Support for Ruby 2.6

---

cookbooks/security_updates/recipes/default.rb

-------------
This PR updates the `net-misc/curl` and `dev-libs/gnutls` packages to the latest versions.
-------------
Apply the latest security updates to curl and gnutls.
Estimated risk
-------------
Low. Just minor version bumps. Package updates are backwards compatible.
-------------
security_updates recipes
-------------
1. Created a testing stack with the changes in this PR.
2. Booted a solo env (Ruby app) and checked (through `emerge -upDN1 world`) that curl and gnutls have updates available.
3. Updated the env to the testing stack and ran Apply.
4. Checked that curl and gnutls were on the latest available stable versions.
-------------
Test a PHP application.
Test …

[FB-549] Package security updates

---

cookbooks/php/attributes/php.rb

-------------
Bump the `dev-lang/php` packages to the latest available patch versions.
-------------
Update to the latest available PHP patch versions.
Estimated risk
-------------
Low. Only the PHP package versions have been updated. PHP keeps compatibility within patch versions.
-------------
php recipes
-------------
1. Created a testing stack with the changes in this PR.
2. Booted a stable-v5 solo env (PHP app, PHP 5.6.x) and deployed.
3. Checked everything works. Logged into the instance and verified that an older PHP patch version was used.
4. Updated to the testing stack and applied changes.
5. Checked everything works. Logged into the instance and verified that the latest PHP patch …

[FB-547] Bump PHP versions

---

cookbooks/postgresql/attributes/version.rb
cookbooks/postgresql/recipes/server_install.rb

-------------
This PR updates our `dev-db/postgresql` packages to the latest available versions.
-------------
Update PostgreSQL to the latest available patch versions.
Estimated risk
-------------
Medium. The changes to the recipes are small. However we need to thoroughly test compatibility between the patch versions and upgrade paths.
-------------
postgresql recipes
-------------
0. Created a testing stack with the changes of this PR.
1. Tested booting+deployment of an env (Ruby app) with PostgreSQL versions 9.4.x, 9.5.x, 9.6.x, and 10.x. Verified that the latest respective version got installed and used.
2. Tested upgrade from stable-v5 to the testing stack. Verified that the …

[FB-573] Update PostgreSQL versions

---

cookbooks/mysql/attributes/version.rb
cookbooks/mysql/recipes/install.rb

-------------
This PR enables the latest versions for the `dev-db/percona-server` packages.
-------------
Support for the latest available Percona Server patch versions.
Estimated risk
-------------
Medium. Changes to the cookbooks are very small, but compatibility and upgrade paths between versions need to be thoroughly tested.
-------------
mysql recipes
-------------
Created a testing stack with the changes in this PR
**Scenario 1**
1. Booted a staging env (Ruby app, MySQL 5.6.x) and deployed the app.
2. Verified it works.
3. Logged into the database master and application master instances and verified that the latest available version of `dev-db/percona-server` in the 5.6 series was …

[FB-548] Bump percona-server versions for 5.6 and 5.7

---

cookbooks/emerge/definitions/package_use.rb
cookbooks/emerge/definitions/package_use_clear.rb
cookbooks/ruby/attributes/versions.rb
cookbooks/ruby/libraries/helpers.rb
cookbooks/ruby/recipes/jemalloc.rb
cookbooks/ruby/recipes/ruby.rb

-------------
This PR adds support for Ruby with jemalloc enabled.
It is available for Ruby 2.4, 2.5, and 2.6. To enable jemalloc for Ruby, set the environment variable `EY_RUBY_JEMALLOC` to `true`.
-------------
Support for Ruby with jemalloc.
Estimated risk
-------------
High. There are a few changes in the ruby recipe which is a central recipe.
-------------
ruby recipes
-------------
Created a testing stack with the changes in this PR.
1. Booted an environment for a Ruby app and selected Ruby 2.5.
2. Deployed and verified it works.
3. Added the environment variable `EY_RUBY_JEMALLOC=true` and applied again.
4. Verified that ruby got re-installed and compiled with jemalloc.
6. Verified …

[FB-522] Support for jemalloc-enabled Ruby

---

cookbooks/openssl/attributes/openssl.rb
cookbooks/security_updates/recipes/default.rb

-------------
This PR updates 'dev-libs/openssl` to it's latest version.
-------------
Apply latest security updates to `openssl`
Estimated risk
-------------
Medium
-------------
openssl cookbook(`attributes/openssl.rb`)
-------------
- Booted a solo env (Ruby app) and checked (through emerge -upDN1 world ) that `openssl` have updates available.
- Updated the local chef recipes(In the instance) with the changes in this PR.
- Executed `/home/ey/bin/chef-solo -j /etc/chef/dna.json -c /etc/chef/solo.rb`
- Checked openssl is updated to the latest version available (`dev-libs/openssl`) .
-------------
- Test a PHP application
- Test different environment configurations

[FB-655] Update openssl

---

cookbooks/security_updates/recipes/default.rb

-------------
This PR updates 'net-misc/openssh` to it's latest version.
-------------
Apply latest security updates to `openssh`
Estimated risk
-------------
Medium
-------------
security updates recipe
-------------
- Booted a solo env (Ruby app) and checked (through `emerge -upDN1 world` ) that `openssh` have updates available.
- Updated the local chef recipes(In the instance) with the changes in this PR.
- Executed `/home/ey/bin/chef-solo -j /etc/chef/dna.json -c /etc/chef/solo.rb`
- Checked `openssh` is updated to the latest version available (eix net-misc/openssh) .
-------------
- Test a PHP application
- Test different environment configurations

[FB-656] Security Updates for openssh vulnerabilities

---

custom-cookbooks/yarn/cookbooks/yarn/README.md

Fixes typo in installation example of yarn README

Fix typo in installation example of yarn README

---

cookbooks/php/attributes/php.rb

-------------
This updates the default PHP versions of PHP71 and PHP72 to v7.1.31 and v7.2.21 respectively.
-------------
This performs an upgrade to the latest installed versions of PHP under the relevant stack.
Estimated risk
-------------
-------------
PHP Cookbook
-------------
1. Boot a PHP environment with PHP versions  5.5, 5.6, 7.0, 7.1 and 7.2 respectively and check if the following versions of PHP is installed.
- PHP4 => '5.6.40'
- PHP5.5 => '5.6.40'
- PHP5.6 => '5.6.40'
- PHP7.0 =>  '7.0.33'
- PHP7.1 => '7.1.31'
- PHP7.2 => '7.2.21'
2. Boot a PHP environment and then upgrade the stack to a later version. Set apply for the whole environment and Change the Stack version of the …

[FB-846] Update PHP version

---

cookbooks/db_admin_tools/recipes/percona_toolkit.rb

Bumping percona toolkit version
Bump percona toolkit version to 2.2.20
Low
DB admin tools
Boot QA stack. 
Verify that version 2.2.20 of perkona toolkit is installed

Bumping Percona Toolkit version to 2.2.20

---

cookbooks/le/attributes/default.rb
cookbooks/le/recipes/configure.rb
custom-cookbooks/le/cookbooks/custom-le/README.md
custom-cookbooks/le/cookbooks/custom-le/attributes/default.rb

-------------
Adds functionality to allow customers to specify application logs for Logentries to follow in the custom recipe's attributes.
-------------
Updated Logentries recipe to allow application logs to be easily added.
Estimated risk
-------------
Low - main recipe has had attributes updated too in order to set new variable required, so will continue to work even if custom recipe not updated by the customer.
-------------
All customers will get new main recipe, only customers who update custom recipe will see new functionality.
-------------
Booted environment with LE enabled. Tested adding new logs to custom attributes, they were added by LE. Also tested with individual logs …

Adds application log LE following to custom attributes

---

cookbooks/passenger5/recipes/monitoring.rb

-------------
Change the default passenger memory limit from `800MB` to `250MB`
-------------
Through this PR, the current default memory limit of 800MB for `passenger` would be reverted back to 250MB
Estimated risk
-------------
Security Risk not applied. The number of possible worker limit would get increased for each instance
-------------
`passenger-5` cookbook
-------------
1. Boot a new instance under new stack version 
2. Check the current memory limit by studying `crontab -e`, regarding the memory about defined as a parameter of `/engineyard/bin/passenger_monitor`
-------------
1. Check with a solo environment
2. Check for environments with multiple instances

[FB-652] Changing the Default Memory Limit to 250MB

---

cookbooks/openssl/attributes/openssl.rb

-------------
Update the default `openssl` version of stack-v5 to `1.0.2t`
-------------
Updates the default `Openssl` version to the latest available via the portage tree.
Estimated risk
-------------
-------------
`openssl` cookbook
-------------
1. Create a new `labrea` release with the branch `FB-1919-Update-OpenSSL-version`
2. Boot a new environment with the above stack release
3. Check for the current `openssl` version via `eix dev-libs/openssl`
-------------
1. Check the current version in a solo environment
2. Check the current version in a multi environment

[FB-1919] Update default OpenSSL version

---

cookbooks/haproxy/attributes/haproxy.rb

-------------
Update the default `haproxy` version of the stack to `1.6.5-r2`
-------------
The cookbooks already update haproxy, to it's latest version, therefore there is no much impact from this commit. But to maintain the consistency, if a cookbook modification is done in the future, the latest available version would be added as the default version.
Estimated risk
-------------
-
-------------
`haproxy` cookbook
-------------
1. Added the latest version to cookbooks.
2. Created a new stack release with the made changes (branch)
3. Checked for the current version
-------------
1. Check the latest version on a solo environment.
2. Check the latest version on a …

[FB-1918] Update Default haproxy Version

---

cookbooks/haproxy/recipes/configure.rb
cookbooks/haproxy/templates/default/haproxy.cfg.erb

This fix allows nginx logging of client (real) IP on the first column of nginx application log.
Nginx is now correctly logging client IP on solo instances 
Low
HAproxy
Boot solo instance, verify that /var/log/nginx/<app>.log is showing client IP on the first column
Test using SSL cert/without
Test with solo + multiple instance envs

Replace 127.0.0.1 with private hostname on solo instances

---

cookbooks/php/attributes/php.rb

-------------
This updates the default PHP versions of PHP71 and PHP72 to v7.1.33 and v7.2.24 respectively.
-------------
This performs an upgrade to the latest installed versions of PHP under the relevant stack.
Estimated risk
-------------
-------------
`PHP` Cookbook
-------------
1. Boot an environment with the development stack. Check for the current version of PHP installed, under `PHP71` and `PHP72`
2. Create a new release in `labrea` with the current branch.
3. Upgrade the environment to the latest stack release from the branch.
4. Verified the versions are upgraded to to v7.1.33 and v7.2.24 respectively
-------------
1. Check version upgrades under a solo …

[FB-1917] PHP Version Update

---

cookbooks/security_updates/recipes/default.rb

-------------
This PR updates the sudo package to the latest available version which fixes CVE-2019-14287.
-------------
Fixes CVE-2019-14287 in the sudo package.
Estimated risk
-------------
Low - only a minor package version bump
-------------
security_updates recipes
-------------
1. Booted a v5 environment with the current release.
2. Updated to a testing stack with this PR.
3. Checked if deploy and app works.
4. Checked if latest sudo version got installed.
-------------
Test with a PHP application.
Test booting a new environment directly with this change.

[FB-1619] Update sudo to the latest version

---

cookbooks/nginx/templates/default/nginx-plusplus.conf.erb

This patch adds all 3 private network ranges to the list of IPs that nginx's considers as trusted sources to extract the real IP of client from
Fixes logging of the real IP on custom networks (VPCs)
Low
nginx
none
Boot QA stack
Verify that chef run / deployment finishes successfully
Verify that the real IP of the client is being logged
Use HTTP/HTTPs traffic to test
Verify on solo / multi instance envs
Use different VPCs (with different CIDRs) to verify

[FB1960] Logging the real IP on custom networks CIDR on NGINX

---

cookbooks/delayed_job4/templates/default/dj.erb

Sourcing environment variables on `DJ` scripts
Sourcing environment variables on `DJ` scripts
Low
Delayed Jobs
none
Use `/etc/init.d` scripts for `DJ` to verify that jobs can be stoped/restarted/started 
Use monit to restart background jobs, verify that no issue exists

[FB1934] Sourcing env vars in DJ workers

---

cookbooks/postgresql/attributes/version.rb
cookbooks/postgresql/recipes/server_install.rb

-------------
Updates the default postgreSQL versions of v9.4, v9.5, v9.6 and of v10 to `9.4.24` , `9.5.19`, `9.6.15` and `10.10` respectively.
-------------
Updates the default postgreSQL versions of v9.4, v9.5, v9.6 and of v10 to `9.4.24` , `9.5.19`, `9.6.15` and `10.10` respectively.
Estimated risk
-------------
-------------
`postgresql` cookbook
-------------
1. Created a new stack release via labrea with the changes done on `postgresql` cookbook.
2. Booted separate envs with the specified postgreSQL main versions.
3. Verified if the latest version available under each key-version is the default one.
-------------
1. Verify the postgresql versions of each `v9.4, v9.5, …

[FB-854] Update PostgreSQL versions

---

cookbooks/db_client_libs/recipes/default.rb
cookbooks/security_updates/recipes/default.rb

-------------
Updates the `net-dns/libidn` and `sys-libs/glibc` to the latest available `stable` version upon a release.
-------------
Updates the current `net-dns/libidn` and `sys-libs/glibc` versions to the latest available stable version.
Estimated risk
-------------
-
-------------
`security_updates` cookbook
-------------
1. Created a new labrea stack release with the specified changes on version upgrades on `security_updates` cookbook.
2. Upgraded the current stack version, to the latest release.
3. Checked if the current versions of the 2 packages are latest.
-------------
1. Boot a solo environment and check if the latest available versions of the `net-dns/libidn` …

[FB-1200] Update glibc and libidn versions to latest stable versions

---

cookbooks/env_vars/libraries/helpers.rb

-------------
Removes code from `env_vars` helper file which were used in Encryption and Decryption scnearios
-------------
Removed the encryption and decryption code blocks from the helper module pf `ey-libs`, such that it doesn't affect the overall functionality of the cookbooks.
Estimated risk
-------------
Low - Nothing majorly included
-------------
`ey-libs` env-vars `helper` module
-------------
- Created a new branch with the changes made on `ey-libs` helper module.
- Created a new `labrea` release with that branch
- Changed the environment to a production stack and added a few environment variables.
- Added `environment variables` via the dashboard and changed the stack back to …

[FB-675] Removed Encryption and Decryption from Environment Vars

---

cookbooks/git/attributes/git.rb
cookbooks/security_updates/recipes/default.rb

-------------
Update the default version of `dev-vcs/git` to `2.7.3-r4`
-------------
Update the default version of `dev-vcs/git` to `2.7.3-r4`
Estimated risk
-------------
Low, updated through `security_updates` package. The current `git` cookbook is not referred while generating the installation
-------------
`security_updates` cookbook
-------------
1. Booted an environment (solo)
2. Edit was made to the `security_updates` cookbook to install the latest default stable version of git
3. Used `/home/ey/bin/chef-solo -j /etc/chef/dna.json -c /etc/chef/solo.rb` to run the cookbooks
4. Verified via `eix dev-vcs/git` if the latest version is installed.
-------------
1. Boot a …

[FB-2128] Update the default Git Version to the latest available

---

cookbooks/app/recipes/prep.rb
cookbooks/ey-lib/libraries/ey-environment.rb
cookbooks/postgresql/attributes/version.rb
cookbooks/util/recipes/prep.rb

This PR adds support for Aurora PostgreSQL database engines. This includes support for Aurora PostgreSQL 10.x.
Adds support for Aurora PostgreSQL.
Medium.
app recipes, util recipes, ey-lib libraries, postgresql recipes
None.
1. Created a Aurora PostgreSQL 10.x RDS Database service
2. Created an environment (Ruby) with Amazon RDS DB provider and Aurora PostgreSQL 10.x DB engine.
3. Booted the environment with two app instances, and a redis utility instance, connected it to the RDS Database service.
4. Checked if Chef run finishes successfully and deployment succeeds.
5. Checked if the deployed application works.
Test a PHP application.
Test with RDS MySQL 5.7, PostgreSQL 9.6, and Aurora MySQL

[TEY-25, TEY-139] Support for Aurora PostgreSQL

---

cookbooks/env_vars/templates/default/env.cloud.erb

-------------
Fixes the env_var cookbook which generates the variables for the environment from the EngineYard UI
-------------
Fixed PHP environmental variables
Estimated risk
-------------
High. Its a main cookbook and its run on ever instance however currently PHP is unable to start if environment variables are set 
-------------
Booted multiple environments one PHP and one Ruby
Set custom variables on both instances
Pressed Apply
Checked that the correct variable was created
-------------
Boot up an environment of your choice. Ruby, PHP, or NodeJS
Set `Environment Variables` via the EngineYard UI
Press apply
Make sure the application server process is able to start and there are no errors, …

[FB-873] fixes php environmental variables [ZD-160560]

---

cookbooks/app/recipes/build.rb

-------------
This PR fixes the logic for including the recipe `mysql::setup_app_users_dbs`.
-------------
Fixes a bug with configuring Aurora MySQL.
Estimated risk
-------------
Low. Just updated the check for including the recipe.
-------------
app recipes
Dependencies
-------------
None
-------------
1. Booted a new environment with an Aurora MySQL 5.6 database.
2. Verified that the deploy fails because the mysql DB user wasn't set up.
3. Upgraded to a dev stack with the changes in this PR.
4. Applied and checked if Chef run is successful.
5. Checked if deployment works and app works.
-------------
Test a PHP application
Test with different app servers.

[TEY-142] Fix logic for including recipe mysql::setup_app_users_dbs

---

custom-cookbooks/custom-addtrust/README.md
custom-cookbooks/custom-addtrust/metadata.rb
custom-cookbooks/custom-addtrust/recipes/default.rb

Added custom-addtrust recipe that removes the expired AddTrust certificate.
N/A
Low
README
- On a V5 environment issue `head /etc/ca-certificates.conf` and check that `mozilla/AddTrust_External_Root.crt` is included
- Test a url using the expired certificate. Output would be of the following type:
```
curl https://expiredrootcertdomainname.com
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html
curl performs SSL certificate verification by default, using a "bundle"
of Certificate Authority (CA) public keys (CA certs). If the default
bundle file isn't adequate, you can specify an alternate file
using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
the bundle, …
```

Added custom-addtrust recipe

---

custom-cookbooks/custom_nodejs/README.md
custom-cookbooks/custom_nodejs/cookbooks/custom_nodejs/README.md
custom-cookbooks/custom_nodejs/cookbooks/custom_nodejs/attributes/default.rb
custom-cookbooks/custom_nodejs/cookbooks/custom_nodejs/files/default/nodejs-bin-generic.ebuild
custom-cookbooks/custom_nodejs/cookbooks/custom_nodejs/metadata.rb
custom-cookbooks/custom_nodejs/cookbooks/custom_nodejs/recipes/default.rb
custom-cookbooks/custom_nodejs/cookbooks/ey-custom/metadata.rb
custom-cookbooks/custom_nodejs/cookbooks/ey-custom/recipes/after-main.rb
custom-cookbooks/custom_nodejs/cookbooks/node/recipes/common.rb

-------------
Adds a port of the [stable-v4 custom_nodejs](https://github.com/engineyard/ey-cloud-recipes/tree/master/cookbooks/custom_nodejs) recipe to allow versions of Node.js outside of portage on the v5 stack.
-------------
Allows the customisation of installed Node.js version outside of those offered in the environment configuration page.
Estimated risk
-------------
Low - custom recipe only used by those requiring it.
-------------
This recipe and an overlay of the `common.rb` in the main `node` recipe.
-------------
v5 instance booted, recipe enabled, versions 10.13 and 12.18 of node set in the attributes and successfully installed. Recipe disabled but `common.rb` overlay left in …

TEY-385 - Adds custom_nodejs recipe

---

cookbooks/ey-lib/libraries/ey-environment.rb
cookbooks/ruby/attributes/versions.rb

**Description of your patch**
This PR updates the minor versions of Ruby 2.4, 2.5, and 2.6.
**Recommended Release Notes**
Updates to the latest available Ruby versions (2.4.10, 2.5.8, 2.6.6). Updates rake to 12.3.3 from 12.3.2. and JSON to 2.3.0 
**Estimated risk**
Medium. Just minor version bump which includes dependencies and security patches
**Components involved**
Ruby recipes
EngineYard Libraries (ey-lib)
**Description of testing done**
Boot new stack -> new Ruby version used
Boot new stack w/jemalloc -> new Ruby w/jemalloc version used
Boot old stack -> upgrade -> new Ruby version used
Boot old stack w/jemalloc -> upgrade -> new Ruby w/jemalloc version used
**QA Instructions**
Test different app server and DB configurations.
Test a PHP application.
Test different environment …

[TEY-242] updates ruby version and dependencies

---

custom-cookbooks/custom_nodejs/cookbooks/node/recipes/common.rb

Fixes issue of instance failing to boot with custom NodeJS version
Fixes custom NodeJS
Estimated risk
Low - custom recipe only used by those requiring it.
This recipe and an overlay of the common.rb in the main node recipe.
v5 instance booted, recipe enabled, versions 10.13 and 12.18 of node set in the attributes and successfully installed. Recipe disabled but common.rb overlay left in place to ensure normal node installation worked successfully. Recipe and overlay removed to ensure that dashboard set version of Node is installed and is changeable via edit environment page.
booted new instance on environment and ensured it booted up successfully 
A new environment should be …

[FB-2824] fixes nodeJS version failing on newly booted instance

---

cookbooks/haproxy/recipes/default.rb

**Description of your patch**
Enables a setting on ethernet to ensure AWS load balancers work correctly
**Recommended Release Notes**
AWS loadbalancer fix
**Estimated risk**
Medium
**Components involved**
haproxy
**Description of testing done**
**QA Instructions**
* Create an AWS load balancer 
* Set up health checks for http
* Boot a T2 instance
* Deploy an application that is accessible by http
* Try and connect by load balancer make sure it doesn't return 503
* Check load balancer health in console

[FB-3898] Fixes TCP issue with ENA drivers and loadbalancers using T2 instances

---

custom-cookbooks/sidekiq/cookbooks/custom-sidekiq/README.md

-------------
Updates the custom-sidekiq readme to correct the way the instance name is specified in the deploy hook from a non-working symbol to a working string.
Also adds to the readme the requirement to use the redis-namespace gem.
-------------
None needed.
Estimated risk
-------------
Zero, is just a readme change.
-------------
The custom_sidekiq recipe.
-------------
Re-read the README.
-------------
None needed.

[FB-3945] Update custom-sidekiq README

---

cookbooks/newrelic_infra/recipes/default.rb

-------------
Updates the `newrelic_infra` default recipe to follow symlinks when untarring the agent package and thus avoid replacing the `/var/run` to `/run` symlink with a directory, which would result in all PIDs being lost.
-------------
Fixes an issue with the New Relic Infrastructure recipe that could result in the loss of the `run` directory contents and impact the running of services for customers who upgraded the agent version.
Estimated risk
-------------
Low, makes a simple change to the extraction of an archive and only impacts those customers who manually change the version to be installed.
-------------
The `newrelic_infra` cookbook.
-------------
Manually tested a download …

[FB-6312] Fix New Relic Infra untar command

---

cookbooks/ey-base/recipes/bootstrap.rb
cookbooks/security_updates/recipes/default.rb

-------------
1. Adds `ca-certificates` package to chef to keep certificates up to date
-------------
Updated system certificates
Estimated risk
-------------
Moderate/High - Is required to avoid errors with external sources using X1 LetsEncrypt
-------------
1. `security` chef recipe 
2. `ey-base` chef recipe 
Dependencies
-------------
None
-------------
* Created environment
* Booted up solo instance
* Run eix ca-certificates 
* curled letsencrypt based website
-------------
* Create environment any configuratiin
* Boot up instances either solo or multi-instances
* Ensure chef runs correctly and entirely
* SSH into instance
* run eix ca-certificates
* curl / openssl …

[FB-9088] Updates certificates and moves it to a better location
