engineyard/ey-cookbooks-stable-v5

cookbooks/ey-monitor/files/default/sshd_config
=> Update sshd_config per Distribution's request to improve security configuration

MoreCookbooks.md, README.md, cookbooks/ey-custom/metadata.rb, cookbooks/ey-init/recipes/main.rb, cookbooks/redis/README.md, cookbooks/redis/attributes/default.rb, cookbooks/redis/metadata.rb, cookbooks/redis/recipes/default.rb, cookbooks/redis/templates/default/redis.conf.erb, cookbooks/redis/templates/default/redis.monitrc.erb, cookbooks/redis/templates/default/redis.yml.erb, examples/hello_world/README.md, examples/hello_world/cookbooks/ey-custom/metadata.rb, examples/hello_world/cookbooks/ey-custom/recipes/before-main.rb, examples/hello_world/cookbooks/hello_world/metadata.rb, examples/hello_world/cookbooks/hello_world/recipes/default.rb, examples/redis/README.md, examples/redis/cookbooks/ey-custom/metadata.rb, examples/redis/cookbooks/ey-custom/recipes/after-main.rb
Redis optional cookbook with example
Hello World custom cookbook example
Documentation on custom cookbooks
=> Documentation and Examples

cookbooks/passenger5/recipes/monitoring.rb
Clean Up Passenger 5 monitoring recipe
=> Clean Up Passenger 5 monitoring recipe

MoreCookbooks.md, cookbooks/sequelizejs/README.md, cookbooks/sequelizejs/attributes/default.rb, cookbooks/sequelizejs/metadata.rb, cookbooks/sequelizejs/recipes/default.rb, cookbooks/sequelizejs/templates/default/config.json.erb
Add optional recipe for installing sequelizejs ORM for NodeJS apps.
=> Add sequelizejs optional recipe

cookbooks/node/attributes/node.rb
Added NodeJS 6.4.0 to available node versions
=> CC-1033 Make NodeJS 6.4.0 available in attributes

cookbooks/nginx/recipes/default.rb
Resolved typo of do for CC-1030
=> Resolve block issue

cookbooks/delayed_job4/README.md, cookbooks/delayed_job4/attributes/default.rb, cookbooks/delayed_job4/recipes/default.rb, examples/delayed_job4/README.md, examples/delayed_job4/cookbooks/custom-delayed_job4/README.md, examples/delayed_job4/cookbooks/custom-delayed_job4/attributes/default.rb, examples/delayed_job4/cookbooks/custom-delayed_job4/metadata.rb, examples/delayed_job4/cookbooks/custom-delayed_job4/recipes/default.rb, examples/delayed_job4/cookbooks/ey-custom/metadata.rb, examples/delayed_job4/cookbooks/ey-custom/recipes/after-main.rb
=> Dj attributes and README

cookbooks/custom_postgresql_maintenance/attributes/default.rb, cookbooks/custom_postgresql_maintenance/recipes/default.rb, cookbooks/postgresql_maintenance/README.md, cookbooks/postgresql_maintenance/attributes/default.rb, cookbooks/postgresql_maintenance/metadata.rb, cookbooks/postgresql_maintenance/recipes/default.rb
=> postgresql_mainteance cookbook ported from ey-cloud-recipes

cookbooks/elasticsearch/recipes/install.rb
=> BUGFIX: missing ['dna']

cookbooks/nginx/recipes/default.rb
Reverts engineyard/ey-cookbooks-stable-v5#25
=> Revert "add haproxy restart for .pem template"

cookbooks/node/attributes/node.rb
Fixup for environments without the feature flag ever turned on.
=> CC-1048 NodeJS dashboard selection Update

cookbooks/node/attributes/node.rb
Fix nodejs selection for customers without the feature and also running nodejs environments.
=> Fix nodejs feature select for nodejs applications

manifest/Gemfile, manifest/Gemfile.lock
Update resin to include ey_services_setup
This update resolves an issue with the ey config gem on stable v5
High
Resin
1. Boot stack under V5 with resin
2. Verify chef runs correctly
3. Verify deploy finishes
4. Add an add on to the environment
5. Deploy
6. Verify that the ey-services-config.yml is created in the shared directory
1. Boot stack under V5 with resin
2. Verify chef runs correctly
3. Verify deploy finishes
4. Add an add on to the environment
5. Deploy
6. Verify that the ey-services-config.yml is created in the shared directory
=> ENG-1145 resin update to include ey_services_setup

cookbooks/passenger5/recipes/install.rb
This patch resolves an issue with Passenger 5 and ssl certificates.
Related YT: https://tickets.engineyard.com/issue/CC-1070
Resolves an issue with SSL Certificates and Passenger 5
Minimal. 
1. Boot an environment with Passenger 5 and an ssl certificate
2. Verify chef fails
3. Upgrade to target stack
4. Verify chef completes
See testing done above
=> CC-1070 Passenger 5 SSL Issue

cookbooks/unicorn/recipes/install.rb
Please refer to CC-1062 and https://github.com/engineyard/ey-cookbooks-stable-v5/pull/66 for details
=> Typo fix for CC-1062-1

cookbooks/passenger5/recipes/install.rb
https://tickets.engineyard.com/issue/CC-1082
Broken node method value in passenger5. Fixed in PR
=> Fix ssh_username value in passenger5 recipe

cookbooks/newrelic/providers/default.rb, cookbooks/newrelic/recipes/default.rb, cookbooks/newrelic/templates/default/newrelic.cfg.erb, cookbooks/newrelic/templates/default/nrsysmond.monitrc.erb
More changes to get newrelic running on php (including php 7.0)
=> Newrelic php

examples/elasticsearch/cookbooks/custom-elasticsearch/README.md
=> Clean up the Elasticsearch README - Custom Cookbook

cookbooks/sidekiq/attributes/default.rb, cookbooks/sidekiq/recipes/cleanup.rb, cookbooks/sidekiq/recipes/setup.rb, cookbooks/sidekiq/templates/default/sidekiq.monitrc.erb
Reverts engineyard/ey-cookbooks-stable-v5#64
=> Revert "Allowed configuring workers independently"

cookbooks/papertrail/attributes/default.rb, cookbooks/papertrail/recipes/default.rb
app_name is reference at attribute/default.rb
=> Move extracted variables to its properplace

cookbooks/packages/README.md, cookbooks/packages/attributes/default.rb, cookbooks/packages/metadata.rb, cookbooks/packages/recipes/default.rb, examples/packages/cookbooks/custom-packages/README.md, examples/packages/cookbooks/custom-packages/attributes/default.rb, examples/packages/cookbooks/custom-packages/metadata.rb, examples/packages/cookbooks/custom-packages/recipes/default.rb, examples/packages/cookbooks/ey-custom/metadata.rb, examples/packages/cookbooks/ey-custom/recipes/after-main.rb
Adds a custom chef recipe for installing a list of packages on all instances under the environment
=> Port the packages recipe from v4

cookbooks/timezone/README.md, cookbooks/timezone/attributes/default.rb, cookbooks/timezone/metadata.rb, cookbooks/timezone/recipes/default.rb, examples/timezone/README.md, examples/timezone/cookbooks/custom-timezone/README.md, examples/timezone/cookbooks/custom-timezone/attributes/default.rb, examples/timezone/cookbooks/custom-timezone/metadata.rb, examples/timezone/cookbooks/custom-timezone/recipes/default.rb, examples/timezone/cookbooks/ey-custom/metadata.rb, examples/timezone/cookbooks/ey-custom/recipes/after-main.rb
Note: Not to be confused with timezones cookbook.
* Using attributes/default.rb to follow the cookbook wrapper pattern.
* There's an attribute that accepts other services to restart when timezone is changed. It has a limitation of being run in all server roles though.
=> Timezone (for changing server timezone)

cookbooks/cron/README.md, cookbooks/cron/attributes/cron.rb, cookbooks/cron/recipes/default.rb, examples/cron/.gitignore, examples/cron/README.md, examples/cron/cookbooks/custom-cron/README.md, examples/cron/cookbooks/custom-cron/attributes/default.rb, examples/cron/cookbooks/custom-cron/metadata.rb, examples/cron/cookbooks/custom-cron/recipes/default.rb, examples/cron/cookbooks/ey-custom/metadata.rb, examples/cron/cookbooks/ey-custom/recipes/after-main.rb
Adds the custom-cron and cron custom Chef cookbooks
Adds the cron custom Chef cookbook
Low.
cron custom Chef cookbook
Run the test cases in examples/cron/cookbooks/custom-cron/README.md
=> Cron from v4

examples/redis/cookbooks/custom-redis/README.md, examples/redis/cookbooks/ey-custom/metadata.rb, examples/redis/cookbooks/ey-custom/recipes/after-main.rb
This fixes an issue found while testing the changes to the Redis recipe
=> Fixes ey-custom inside examples/redis/cookbooks

cookbooks/memcached/templates/default/memcached.monitrc
This fixes an issue found during testing of the memcached recipe
=> Fixes memcached.monitrc

examples/delayed_job4/cookbooks/custom-delayed_job4/README.md
Correcting a typo on "after_restart" hook example
N/A
Low
README
No QA needed
=> fixing after_restart hook example

examples/sidekiq/cookbooks/custom-sidekiq/README.md
Add instructions on how to parse redis.yml
=> Update Sidekiq recipe README.

cookbooks/redis/attributes/default.rb, cookbooks/redis/recipes/install.rb, cookbooks/redis/templates/default/redis-2.8-slave.conf.erb, cookbooks/redis/templates/default/redis-3.2-slave.conf.erb, cookbooks/redis/templates/default/redis-4.0-slave.conf.erb, examples/redis/cookbooks/custom-redis/README.md, examples/redis/cookbooks/custom-redis/attributes/default.rb
This addresses https://github.com/engineyard/ey-cookbooks-stable-v5/issues/134
=> Add support for Redis slave replication

examples/redis/cookbooks/custom-redis/README.md
Correcting README instructions
N/A
Low
README
No QA needed
=> Redis documentation

cookbooks/node/recipes/common.rb, cookbooks/node/recipes/yarn.rb
Install yarn alongside node and npm
=> Initial support for yarn

cookbooks/node/attributes/yarn.rb, cookbooks/node/files/default/yarn-0.21.3.ebuild, cookbooks/node/recipes/yarn.rb
Complete rewrite to make the recipe Gentoo friendly
=> Install yarn using a Gentoo ebuild

cookbooks/node/attributes/node.rb
Commas were missing on PR #169 :|
=> Fix syntax errors

cookbooks/le/README.md, custom-cookbooks/le/cookbooks/custom-le/README.md, custom-cookbooks/le/cookbooks/custom-le/attributes/default.rb, custom-cookbooks/le/cookbooks/ey-custom/metadata.rb, custom-cookbooks/le/cookbooks/ey-custom/recipes/after-main.rb
Adds ey-custom
Removes hard-coded sample key in attributes/default.rb
Fixes README
=> Minor fixes on Logentries custom recipe

cookbooks/ey-cron/recipes/default.rb
This should resolve issue #189 .
=> Include PHP_ENV env var in crontab.

cookbooks/passenger5/recipes/install.rb
This fixes the reported error in https://github.com/engineyard/ey-cookbooks-stable-v5/pull/193
=> Patch for CC-1058

cookbooks/timezones/recipes/default.rb
Corrects issue introduced by PR#173
=> revision to timezone service restarts

cookbooks/postgresql/files/default/load_postgres_db.sh
Correctly detect and fix permissions of materialized views.
=> Fix permissions of materialized views

cookbooks/sidekiq/recipes/setup.rb
This is patch for PR #210. Please follow the QA instructions in #210.
=> CC-1185 chown existing log sidekiq log files

cookbooks/elasticsearch/recipes/install.rb
The app-servers wasn't getting the `elasticsearch.yml`-file, I fixed that.
=> Missing elasticsearch.yml on app servers

custom-cookbooks/elasticsearch/cookbooks/custom-elasticsearch/README.md
- added instructions on how to set JVM options
- added instructions on how to specify the version
=> Update elasticsearch README.md

cookbooks/security_updates/recipes/default.rb
-------------
Pulls in =app-admin/sudo-1.8.16-r1 which contains security fixes
-------------
Update to =app-admin/sudo-1.8.16-r1 addressing multiple vulnerabilities.
Estimated risk
-------------
Low
-------------
app-admin/sudo
-------------
Local chef run
-------------
Make sure things don't break and that app-admin/sudo gets upgraded (see qlop --list sudo).
=> CC-1187: Update to =app-admin/sudo-1.8.16-r1 addressing multiple vulnerabilities

cookbooks/env_vars/recipes/cloud.rb, cookbooks/env_vars/recipes/default.rb
Do not attempt to restart the application if
- perform_restart is set to false
- the file /engineyard/bin/app_APPNAME does not exist
=> env_vars: Add checks on perform_restart

manifest/Gemfile, manifest/Gemfile.lock
--------------
Enhancements and bug fixes for eybackup/ey_cloud_server.
--------------
- Adds support for logical backups of RDS databases
- Adds automatic database engine detection based on the environment DNA
Estimated risk
--------------
Medium
- Logical backups are a critical path component of the Engine Yard stack, these changes have been carefully reviewed prior to preparing this release.
--------------
manifest.yml
--------------
- Updated to the required stack
- Ran a backup
- Ran a restore
- Ran a GPG encrypted backup
- Ran a restore of an encrypted backup and confirmed the restore operation was blocked
- Ran a download of an encrypted backup and …
=> Upgrades to logical backup controls for RDS and auto-engine detection.

cookbooks/solr/recipes/install.rb
To avoid security exceptions when starting Solr
This addresses issue #261
=> [Solr] Upgrade dev-libs/nss to 3.23

cookbooks/security_updates/recipes/default.rb
https://tickets.engineyard.com/issue/CC-1182
=> security update of media-libs/tiff package to the 4.0.8 version

cookbooks/php/attributes/php.rb
https://tickets.engineyard.com/issue/CC-1119
=> dev-lang/php package was updated to the version 5.6.30. Ticket: 1119

cookbooks/openssl/attributes/openssl.rb
https://tickets.engineyard.com/issue/CC-1146
=> openssl version updated Ticket: CC-1146

cookbooks/php/attributes/php.rb
https://tickets.engineyard.com/issue/CC-1119
=> dev-lang/php package was updated to the version 5.6.30. Ticket: CC-1119

cookbooks/mysql/attributes/version.rb, cookbooks/mysql/recipes/install.rb
https://tickets.engineyard.com/issue/CC-1216
=> Updates Percona-Server to 5.6.37 and 5.7.19. Ticket: CC-1216

cookbooks/security_updates/recipes/default.rb
Upgrade dev-libs/libyaml package to the version 0.1.7
None.
Low
dev-libs/libyaml package
1. Create simple Ruby application. Simple TO-DO app (https://github.com/engineyard/todo.git) can be used for this testing.
4. Replace security_updates cookbook with cookbook provided in current pool request.
5. Run Chef `PATH=/usr/local/ey_resin/bin:$PATH /home/ey/bin/chef-solo -j /etc/chef/dna.json -c /etc/chef/solo.rb`
6. Run command `eix dev-libs/libyaml`
7. Ensure you version of installed dev-libs/libyaml package is 0.1.7
=> [CC-1225]Update dev-libs/libyaml

CONTRIBUTING.md, README.md
No testing needed, only README and CONTRIBUTING.mf files were updated
=> contrbution guide added, readme file updated

cookbooks/collectd/recipes/default.rb
-------------
Minor cleanup to collectd recipe dependency package directives
-------------
No recommendations
Estimated risk
-------------
Low
-------------
Cookbooks, EYGL, collectd, perl modules
-------------
Cookbook run succeeds. Did not check collectd graphs.
-------------
After booting with fresh test stack ensure collectd graph functionality did not regress.
=> YT-CC-1239: Minor cleanup to collectd recipe dependency package directives

cookbooks/db_client_libs/README.md, cookbooks/db_client_libs/metadata.rb, cookbooks/db_client_libs/recipes/default.rb
Updated custom db-libs ported from the v4 custom chef recipes for no-db envs
=> [Custom] Update custom db-libs

cookbooks/passenger5/files/default/passenger_monitor
Correcting a typo on "passenger_monitor"
N/A
Low
passenger-monitor script
No QA needed
=> fixing typo on passenger_monitor script

cookbooks/prompt/attributes/default.rb, cookbooks/prompt/recipes/default.rb, cookbooks/prompt/templates/default/prompt.erb
Cookbook providing more informative Bash prompt 
Bash prompt improved with additional information about environment
Low
Bash
1. Create a simple Ruby application.  (https://github.com/engineyard/todo.git) can be used for this testing.
2. Boot the environment with QA stack created from the PR282_improvement branch. Environment should be run with following parameters:
* Application Server Stack - Passenger5.
4. Update `/etc/chef/dna.json file`. Find JSON Hash value:
``` 
"run_list": [
"recipe[ey-init::main]"
],
```
and replace it with
```
"run_list": [
"recipe[ey-init::main]",
"recipe[prompt]"
],
```
5. Run Chef again `PATH=/usr/local/ey_resin/bin:$PATH /home/ey/bin/chef-solo -j /etc/chef/dna.json -c /etc/chef/solo.rb`.
6. Relogin to …
=> [YT-CC-854] Bash prompt message improved

cookbooks/ey-init/recipes/main.rb
Adding prompt recipe in conjunction with https://github.com/engineyard/ey-cookbooks-stable-v5/pull/341
N/A
Low
README
Boot the environment with QA stack
Switch to "deploy" user via `su - deploy` 
Confirm that prompt is providing information
=> adding prompt recipe to main recipes

cookbooks/collectd/attributes/defaults.rb, cookbooks/ey-bin/attributes/ey_monit_scripts.rb, cookbooks/ey-lib/libraries/ey-environment.rb, cookbooks/security_updates/recipes/default.rb, cookbooks/sysklogd/attributes/default.rb
-------------
Bump package versions that have never versions available by default on EYGL `2016.06.019.final` and newer.
-------------
Upgrade packages to latest available versions.
Estimated risk
-------------
Medium. All upgrades are minor version bumps that are backwards compatible.
-------------
EYGL OS packages: collectd, ey-monit-scripts, ruby, curl, libxml2, sysklogd
-------------
Booted environment on an EYGL `2016.06.020.final` OS image.
Verified that upgrades happened and expected versions got installed.
Verified that applications and deploys work as expected.
-------------
Do more detailed testing on different applications and environment configurations.
=> [CC-1254] Bump package versions

cookbooks/passenger5/files/default/passenger_monitor_530, cookbooks/passenger5/recipes/install.rb
Updates passenger cookbook to add monitoring support for passenger v5.3.0 upwards due to the output changes
-----
N/a
-----
High: Edits the default passenger v5 recipe which loaded by environments using passenger, needs to be thoroughly checked before released however is highly needed as memory issues currently happen on passenger version v5.3.0 and over
-----
Passenger, /engineyard/bin
----
* Booted an environment with the custom cookbooks uploaded.
* Checked if the environment works.
* Purposely created a memory leak
* Watched monitor kill the Passenger worker when went over limit
----
* Boot Environment
* Create a snippet in ruby which will trigger a memory leak
* Execute said code with memory leak
* Check `passenger-status`
* See if the worker is killed at 800mb or the set limit
=> Support for passenger 530

cookbooks/delayed_job4/templates/default/dj.erb
Pass the QUEUE parameter to the DJ run command
=> [YT-CC-1243] DelayedJob recipe

cookbooks/ey-base/recipes/chef_patches.rb
-------------
Patch the rubygems provider in Chef to support rubygems 3.x.
-------------
Support for RubyGems 3.x in Chef.
Estimated risk
-------------
High. Chef is a critical component.
-------------
Chef
ey-base recipes
-------------
Created a testing stack and booted a stable-v5 environment. Checked if it works.
Then updated to the testing stack and checked if it works.
On the instance upgraded to rubygems 3.0.3. and uninstalled the unicorn gem.
Ran Chef again and checked if it works.
-------------
Test booting environments with rubygems 3.0.3 directly.
=> [CC-1352] Patch Chef with rubygems 3.x support

cookbooks/nginx/attributes/default.rb, cookbooks/security_updates/recipes/default.rb
-------------
This PR updates `www-servers/nginx` to it's latest version.
-------------
Apply latest security updates to `nginx`
Estimated risk
-------------
Medium
-------------
nginx cookbook (`attributes/default.rb`)
-------------
- Booted a solo env (Ruby app) and checked (through `emerge -upDN1 world` ) that `nginx` have updates.
- Updated the local chef recipes(In the instance) with the changes in this PR.
- Executed `/home/ey/bin/chef-solo -j /etc/chef/dna.json -c /etc/chef/solo.rb`
- Checked whether nginx had been updated to the latest version available (`www-servers/nginx`) .
-------------
- Test a PHP application
- Test different environment configurations
=> [Fb-657] Update Nginx

custom-cookbooks/custom_ca_certs/cookbooks/custom-ca-certs/README.md, custom-cookbooks/custom_ca_certs/cookbooks/custom-ca-certs/libraries/helpers.rb, custom-cookbooks/custom_ca_certs/cookbooks/custom-ca-certs/recipes/default.rb
With regards to recent main cookbooks changes.
=> Updates the custom CA certs recipe

custom-cookbooks/custom_haproxy_ssls/cookbooks/custom-haproxy-ssls/README.md, custom-cookbooks/custom_haproxy_ssls/cookbooks/custom-haproxy-ssls/libraries/helpers.rb, custom-cookbooks/custom_haproxy_ssls/cookbooks/custom-haproxy-ssls/recipes/default.rb
With regards to recent main cookbooks changes.
=> Updates the custom_haproxy_ssls recipe

cookbooks/ey-lib/libraries/ey-environment.rb
-------------
This PR updates the minor versions of Ruby 2.4, 2.5, and 2.6.
-------------
Updates to the latest available Ruby versions (2.4.9, 2.5.7, 2.6.5).
Estimated risk
-------------
Medium. Just minor version bumps.
-------------
Ruby recipes
-------------
Boot new stack -> new Ruby version used
Boot new stack w/jemalloc -> new Ruby w/jemalloc version used
Boot old stack -> upgrade -> new Ruby version used
Boot old stack w/jemalloc -> upgrade -> new Ruby w/jemalloc version used
-------------
Test different app server and DB configurations.
Test a PHP application.
Test different environment configurations.
=> [FB-1596] Minor Ruby Version Updates

cookbooks/collectd/templates/default/collectd.conf.erb
-------------
This PR fixes PostgreSQL checkpoint alerts in the collect.conf.
-------------
Improves the configuration of collect checkpoint checks.
Estimated risk
-------------
Low.
-------------
collected recipes
Dependencies
-------------
None
-------------
PostgreSQL (10) on solo environment
PostgreSQL (10) on a clustered environment
-------------
Test different environment configurations.
=> [TEY-212] Fix postgresql checkpoint checks in collectd config

cookbooks/security_updates/recipes/default.rb
**Description of your patch**
Updates version of sudo installed 
**Recommended Release Notes**
Updated sudo version that is installed.
**Estimated risk**
Low
**Components involved**
Default version of packages
**Description of testing done**
* Built test package
* Made sure package was installed after chef run
=> [FB-5297] Update sudo

cookbooks/ey-lib/libraries/ey-environment.rb, cookbooks/php/attributes/php.rb
Reverts engineyard/ey-cookbooks-stable-v5#464
=> Revert "PHP update"

cookbooks/ey-lib/libraries/ey-environment.rb, cookbooks/security_updates/recipes/default.rb
Reverts engineyard/ey-cookbooks-stable-v5#463
=> Revert "[FB-9046] Update ruby"

cookbooks/ey-lib/libraries/ey-environment.rb, cookbooks/security_updates/recipes/default.rb
Fixes issue where PR 462 / 463 files where removed in commit 
https://github.com/engineyard/ey-cookbooks-stable-v5/pull/464
=> [PR-462 / 463] - Fixes issue off removed files after local branch issue
